const strings = {
  'en': {

    // ─── Language Toggle ───
    LANG_TOGGLE: 'বাংলা',

    // ─── Shared Layout (MobileLayout) ───
    LAYOUT_ONLINE: 'Online',
    LAYOUT_OFFLINE: 'Offline',
    LAYOUT_SYNCING: 'Syncing',
    LAYOUT_ALERTS_BTN: 'Alerts',
    LAYOUT_LOGOUT_BTN: 'Logout',
    LAYOUT_RESPOND_BTN: 'Respond',
    LAYOUT_PORTAL_PATIENT: 'Patient Portal',
    LAYOUT_PORTAL_WORKER: 'Maternal Health Worker Portal',
    LAYOUT_ADMIN_CONSOLE: 'Admin Console',

    // ─── Nav Items (Patient) ───
    NAV_P_HOME: 'Home',
    NAV_P_AICHAT: 'AI Chat',
    NAV_P_HEALTH: 'Health',
    NAV_P_ALERTS: 'Alerts',
    NAV_P_PROFILE: 'Profile',

    // ─── Nav Items (Worker) ───
    NAV_W_HOME: 'Home',
    NAV_W_PATIENTS: 'Patients',
    NAV_W_AI: 'AI',
    NAV_W_SYNC: 'Sync',
    NAV_W_PROFILE: 'Profile',

    // ─── Splash ───
    SPLASH_HEADLINE: 'Offline-First AI Maternal Healthcare',
    SPLASH_SUBLINE: 'AI-powered pregnancy risk monitoring, symptom checking, and automatic database syncing for rural health workers and mothers.',
    SPLASH_CTA: 'Get Started →',
    SPLASH_DISCLAIMER_TITLE: 'Medical Disclaimer',
    SPLASH_DISCLAIMER_BODY: 'PulseGuard is a decision-support tool for trained health workers — it does not replace professional medical advice, diagnosis, or treatment. In case of an emergency, contact a qualified healthcare provider or the nearest clinic immediately.',

    // ─── Role Selection ───
    ROLE_HEADING: 'Choose Your Role',
    ROLE_SUBHEADING: 'Select how you want to log in to the PulseGuard platform',
    ROLE_PATIENT_TITLE: 'Patient / Mother',
    ROLE_PATIENT_DESC: 'Log health data, check pregnancy vitals, and consult the AI assistant offline.',
    ROLE_WORKER_TITLE: 'Health Worker',
    ROLE_WORKER_DESC: 'Register mothers, monitor local vitals, and review AI risk analysis in villages.',
    ROLE_ADMIN_TITLE: 'Administrator',
    ROLE_ADMIN_DESC: 'Manage clinical assignments, inspect system analytics, and view regional summaries.',
    ROLE_CONTINUE: 'Continue →',
    ROLE_BACK: '← Back to Welcome Screen',

    // ─── Login ───
    LOGIN_HEADING: 'Welcome Back',
    LOGIN_SUBHEADING_PREFIX: 'Sign in as',
    LOGIN_SUBHEADING_SUFFIX: 'to access PulseGuard AI',
    LOGIN_LABEL_EMAIL: 'Email Address',
    LOGIN_LABEL_PASSWORD: 'Password',
    LOGIN_PH_EMAIL: 'you@example.com',
    LOGIN_PH_PASSWORD: '••••••••',
    LOGIN_BTN: 'Sign In',
    LOGIN_BTN_LOADING: 'Signing in...',
    LOGIN_LINK_REGISTER: 'Create an Account',
    LOGIN_LINK_CHANGE_ROLE: 'Change Role',
    LOGIN_ERR_PREFIX: 'Error:',

    // ─── Register ───
    REGISTER_HEADING: 'Join PulseGuard AI',
    REGISTER_SUBHEADING_PREFIX: 'Create your',
    REGISTER_SUBHEADING_SUFFIX: 'account to get started',
    REGISTER_LABEL_NAME: 'Full Name *',
    REGISTER_LABEL_EMAIL: 'Email Address *',
    REGISTER_LABEL_PHONE: 'Phone Number',
    REGISTER_LABEL_PASSWORD: 'Password *',
    REGISTER_PH_NAME: "Dr. Sarah Connor or Mother's Name",
    REGISTER_PH_EMAIL: 'you@example.com',
    REGISTER_PH_PHONE: '+880 XXX XXX XXX',
    REGISTER_PH_PASSWORD: 'Create a strong password',
    REGISTER_BTN: 'Create Account',
    REGISTER_BTN_LOADING: 'Creating Account...',
    REGISTER_ALREADY_HAVE: 'Already have an account?',
    REGISTER_LINK_SIGNIN: 'Sign In',
    REGISTER_ERR_PREFIX: 'Error:',

    // ─── Patient Dashboard ───
    PAGE_TITLE_DASHBOARD: 'Dashboard',
    DASH_LOADING: 'Loading health profile…',
    DASH_WELCOME_HEADING_PREFIX: 'Welcome,',
    DASH_WELCOME_BODY: 'Your account is ready! Complete your pregnancy profile to unlock vitals tracking, AI health checks, and personalised guidance.',
    DASH_COMPLETE_PROFILE_BTN: '✓ Complete My Profile',
    DASH_GREETING_PREFIX: 'Hello,',
    DASH_WEEK_LABEL: 'Pregnancy Week',
    DASH_SECTION_QUICK_ACTIONS: 'Quick Actions',
    DASH_ACTION_DAILY_TITLE: 'Daily Health Check',
    DASH_ACTION_DAILY_DESC: "Record today's vitals",
    DASH_ACTION_AI_TITLE: 'AI Symptom Checker',
    DASH_ACTION_AI_DESC: 'Chat with PulseGuard AI',
    DASH_ACTION_NUTRITION_TITLE: 'Nutrition Plan',
    DASH_ACTION_NUTRITION_DESC: 'Personalized meal guide',
    DASH_ACTION_EMERGENCY_TITLE: 'Emergency SOS',
    DASH_ACTION_EMERGENCY_DESC: 'One-tap emergency alert',
    DASH_SECTION_HEALTH_SUMMARY: 'Health Summary',
    DASH_KPI_BP: 'Blood Pressure',
    DASH_KPI_WEIGHT: 'Weight',
    DASH_KPI_TEMP: 'Temperature',
    DASH_KPI_LAST_CHECKUP: 'Last Checkup',
    DASH_KPI_NO_RECORDS: 'No records',
    DASH_VIEW_ALL_RECORDS: 'View All Records →',

    // ─── AI Chat ───
    PAGE_TITLE_AI_CHAT: 'AI Symptom Checker',
    AI_CHAT_PH: 'Describe your symptoms...',
    AI_CHAT_SEND: 'Send',
    AI_CHAT_ERR_OFFLINE: 'Sorry, the AI service is currently offline or unreachable. Please try again later.',
    AI_CHAT_ERR_FAILED: "Sorry, I couldn't process that request.",

    // ─── Daily Health Check ───
    PAGE_TITLE_DAILY_CHECK: 'Daily Health Check',
    DAILY_LOADING: 'Loading daily health check form…',
    DAILY_NO_PROFILE_ICON: '📋',
    DAILY_NO_PROFILE_HEADING: 'Profile Setup Required',
    DAILY_NO_PROFILE_BODY: 'You need to complete your pregnancy profile before recording vitals.',
    DAILY_NO_PROFILE_BTN: 'Complete My Profile',
    DAILY_FORM_HEADING: "Record Today's Vitals",
    DAILY_FORM_DATE_PREFIX: 'Pregnancy Week',
    DAILY_LABEL_BP: 'Blood Pressure (mmHg) *',
    DAILY_PH_BP: 'e.g. 120/80',
    DAILY_LABEL_WEIGHT: 'Weight (kg)',
    DAILY_PH_WEIGHT: 'e.g. 62',
    DAILY_LABEL_TEMP: 'Temperature (°C)',
    DAILY_PH_TEMP: 'e.g. 36.8',
    DAILY_LABEL_PULSE: 'Pulse (bpm)',
    DAILY_PH_PULSE: 'e.g. 75',
    DAILY_LABEL_SYMPTOMS: 'Symptoms (comma-separated)',
    DAILY_PH_SYMPTOMS: 'e.g. Headache, Nausea',
    DAILY_BTN_SAVE: 'Save',
    DAILY_BTN_SAVING: 'Saving...',
    DAILY_BTN_SAVE_OFFLINE: 'Save Offline',
    DAILY_SUCCESS_OFFLINE: 'Saved to offline queue successfully! It will sync when connection is restored.',
    DAILY_SUCCESS_PREFIX: 'Daily check recorded! Risk status',
    DAILY_ERR_NO_PROFILE: 'No patient profile found. Please complete your registration first.',
    DAILY_ERR_BP_REQUIRED: 'Blood pressure is required (e.g. 120/80).',
    DAILY_ERR_BP_FORMAT: 'Please enter blood pressure in the format "systolic/diastolic" (e.g. 120/80)',
    DAILY_ERR_BP_RANGE: 'Invalid BP. Out of range',
    DAILY_ERR_PULSE_RANGE: 'Invalid pulse. Out of range',
    DAILY_ERR_NETWORK: 'Network request failed. Please try saving offline instead.',
    DAILY_ERR_SAVE_LOCAL: 'Failed to save data locally.',

    // ─── Emergency SOS ───
    PAGE_TITLE_EMERGENCY: 'Emergency SOS',
    EMERGENCY_HEADING: 'Emergency Alert',
    EMERGENCY_STATUS_READY: 'PulseGuard Security System: Ready',
    EMERGENCY_STATUS_SENT: 'SOS Dispatched: Help is on the way!',
    EMERGENCY_STATUS_GPS: 'GPS Coordinates:',
    EMERGENCY_STATUS_OFFLINE: 'Offline Mode Active',
    EMERGENCY_BODY: 'Press the SOS button to alert nearby health workers and emergency services. Your GPS location will be shared automatically.',
    EMERGENCY_SOS_BTN: 'SOS',
    EMERGENCY_SOS_SENT: 'SENT',
    EMERGENCY_BTN_GPS_LOADING: 'Fetching Location…',
    EMERGENCY_BTN_GPS: 'Share GPS Location',
    EMERGENCY_BTN_NOTIFY: 'Notify Health Worker',
    EMERGENCY_BTN_CALL: 'Call Emergency Services',

    // ─── Nutrition ───
    PAGE_TITLE_NUTRITION: 'Nutrition Guide',
    NUTRITION_TAG_ALL: 'All',
    NUTRITION_TAG_IRON: 'Iron Rich',
    NUTRITION_TAG_PROTEIN: 'Protein',
    NUTRITION_TAG_CALCIUM: 'Calcium',
    NUTRITION_TAG_VITAMINS: 'Vitamins',
    NUTRITION_SECTION_RECOMMENDED: 'Recommended Foods',
    NUTRITION_SECTION_RECOMMENDED_DESC: 'Essential nutrients for your pregnancy',
    NUTRITION_SECTION_AVOID: 'Foods to Avoid',
    NUTRITION_SECTION_AVOID_DESC: 'Minimize risk during pregnancy',
    NUTRITION_SECTION_LOCAL: 'Local Affordable Foods',
    NUTRITION_SECTION_LOCAL_DESC: 'Nutritious options available in your region',
    NUTRITION_EMPTY_RECOMMENDED: 'No recommended foods match the selected filter.',
    NUTRITION_EMPTY_LOCAL: 'No local foods match the selected filter.',

    // ─── Records ───
    PAGE_TITLE_RECORDS: 'Medical Records',
    RECORDS_HEADING: 'Your Records',
    RECORDS_EXPORT_BTN: '⬇️ Export CSV',
    RECORDS_LOADING: 'Loading records…',
    RECORDS_EMPTY: 'No records recorded yet.',
    RECORDS_FIELD_BP: 'BP:',
    RECORDS_FIELD_WEIGHT: 'Weight:',
    RECORDS_FIELD_TEMP: 'Temp:',
    RECORDS_FIELD_PULSE: 'Pulse:',
    RECORDS_NA: 'N/A',

    // ─── Patient Alerts ───
    PAGE_TITLE_ALERTS: 'Alerts',
    ALERTS_HEADING: 'Notifications',

    // ─── Patient Profile ───
    PAGE_TITLE_PROFILE: 'Profile',
    PROFILE_LOADING: 'Loading profile details…',
    PROFILE_SECTION_DETAILS: 'Profile Details',
    PROFILE_SECTION_EDIT: 'Edit Profile',
    PROFILE_LABEL_PREG_WEEK: 'Pregnancy Week',
    PROFILE_LABEL_RISK: 'Risk Level',
    PROFILE_LABEL_VILLAGE: 'Village',
    PROFILE_LABEL_PHONE: 'Phone',
    PROFILE_LABEL_EMAIL: 'Email',
    PROFILE_LABEL_ASSIGNED_PATIENTS: 'Assigned Patients',
    PROFILE_LABEL_SYSTEM_ROLE: 'System Role',
    PROFILE_LABEL_ADMIN_VALUE: 'Administrator',
    PROFILE_LABEL_PROFILE_STATUS: 'Profile Status',
    PROFILE_LABEL_PENDING: 'Pending Registration Completion',
    PROFILE_BTN_COMPLETE_REG: 'Complete Registration',
    PROFILE_EDIT_LABEL_NAME: 'Full Name *',
    PROFILE_EDIT_LABEL_EMAIL: 'Email Address',
    PROFILE_EDIT_LABEL_PHONE: 'Phone Number',
    PROFILE_EDIT_LABEL_VILLAGE: 'Village Clinic Area',
    PROFILE_EDIT_LABEL_WEEK: 'Gestational Pregnancy Week',
    PROFILE_EDIT_PH_NAME: 'Enter your name',
    PROFILE_EDIT_PH_EMAIL: 'e.g. name@domain.com',
    PROFILE_EDIT_PH_PHONE: 'e.g. +880123456789',
    PROFILE_EDIT_PH_VILLAGE: 'e.g. Village A',
    PROFILE_EDIT_PH_WEEK: 'e.g. 24',
    PROFILE_BTN_SAVE_CHANGES: 'Save Changes',
    PROFILE_BTN_SAVING: 'Saving...',
    PROFILE_BTN_CANCEL: 'Cancel',
    PROFILE_BTN_EDIT: 'Edit Profile',
    PROFILE_BTN_LOGOUT: 'Logout',
    PROFILE_ERR_NAME_REQUIRED: 'Name is required',
    PROFILE_ERR_NAME_LETTERS: 'Name must contain only letters and spaces',
    PROFILE_ERR_PHONE_DIGITS: 'Phone number must be exactly 11 digits',
    PROFILE_SUCCESS: 'Profile updated successfully!',
    PROFILE_PATIENT_ID_PREFIX: 'Patient ID: PG-',
    PROFILE_WORKER_ID_PREFIX: 'Health Worker ID: HW-',

    // ─── Onboarding ───
    PAGE_TITLE_ONBOARDING: 'Set Up Profile',
    ONBOARD_WELCOME_PREFIX: 'Welcome,',
    ONBOARD_WELCOME_BODY: 'To get started with PulseGuard, we need a few details to set up your maternal health profile. This will unlock vitals tracking, AI health checks, and personalised guidance.',
    ONBOARD_SECTION_HEADING: 'Medical Profile Setup',
    ONBOARD_SECTION_SUBHEADING: 'All fields marked * are required.',
    ONBOARD_LABEL_WEEK: 'Current Pregnancy Week *',
    ONBOARD_PH_WEEK: 'e.g. 24',
    ONBOARD_HINT_WEEK: 'Enter a value between 1 and 45.',
    ONBOARD_LABEL_AGE: 'Your Age',
    ONBOARD_PH_AGE: 'e.g. 26',
    ONBOARD_LABEL_VILLAGE: 'Village / Clinic Area',
    ONBOARD_PH_VILLAGE: 'e.g. Kurigram Village A',
    ONBOARD_BTN_SUBMIT: '✓ Complete Registration',
    ONBOARD_BTN_LOADING: 'Setting up profile…',
    ONBOARD_ERR_WEEK_REQUIRED: 'Please enter your current gestational week.',
    ONBOARD_ERR_WEEK_RANGE: 'Gestational week must be between 1 and 45.',

    // ─── Worker Dashboard ───
    W_PAGE_TITLE_DASHBOARD: 'Health Worker',
    W_DASH_GREETING_PREFIX: 'Hello,',
    W_DASH_GREETING_DEFAULT: 'Health Worker',
    W_DASH_LOADING: 'Loading your assigned patient overview...',
    W_DASH_PATIENTS_SUFFIX: 'patients assigned, including',
    W_DASH_HIGH_RISK_CASE: 'high risk case today.',
    W_DASH_HIGH_RISK_CASES: 'high risk cases today.',
    W_DASH_BANNER_TITLE: 'Sync Center',
    W_DASH_BANNER_ACTION: 'Open Sync',
    W_DASH_KPI_HEADING: "Today's KPIs",
    W_DASH_KPI_TOTAL: 'Total Patients',
    W_DASH_KPI_HIGH: 'High Risk Cases',
    W_DASH_KPI_MODERATE: 'Moderate Risk Cases',
    W_DASH_KPI_LOW: 'Low Risk Cases',
    W_DASH_SECTION_QUICK: 'Quick Actions',
    W_DASH_QUICK_PATIENTS: 'Patient List',
    W_DASH_QUICK_AI: 'AI Assistant',
    W_DASH_QUICK_SYNC: 'Sync Center',
    W_DASH_SECTION_HIGH_RISK: 'High Risk Patients',
    W_DASH_HIGH_RISK_SUFFIX: 'patients',
    W_DASH_LOADING_LIST: 'Loading…',
    W_DASH_NO_HIGH_RISK: 'No high risk patients',
    W_DASH_VIEW_BTN: 'View',
    W_DASH_SUMMARY_A: 'You have',
    W_DASH_SUMMARY_B: 'patients assigned, including',
    W_DASH_SUMMARY_C: '',

    // ─── Worker Patient List ───
    W_PAGE_TITLE_PATIENTS: 'Patient List',
    W_PATIENTS_SEARCH_PH: 'Search patient by name or village…',
    W_PATIENTS_FILTER_ALL: 'All',
    W_PATIENTS_FILTER_HIGH: 'High Risk',
    W_PATIENTS_FILTER_MODERATE: 'Moderate',
    W_PATIENTS_FILTER_LOW: 'Low Risk',
    W_PATIENTS_HEADING: 'Patients',
    W_PATIENTS_RESULTS_SUFFIX: 'results',
    W_PATIENTS_LOADING: 'Loading patients…',
    W_PATIENTS_EMPTY: 'No patients match your search.',
    W_PATIENTS_WEEK_PREFIX: 'Week',
    W_PATIENTS_UNKNOWN: 'Unknown',
    W_PATIENTS_VIEW_BTN: 'View',

    // ─── Worker Patient Details ───
    W_PAGE_TITLE_PATIENT_DETAILS: 'Patient Details',
    W_DETAILS_LOADING: 'Loading patient…',
    W_DETAILS_NOT_FOUND: 'Patient not found',
    W_DETAILS_AGE_PREFIX: 'Age:',
    W_DETAILS_WEEK_PREFIX: 'Week',
    W_DETAILS_TAB_OVERVIEW: 'Overview',
    W_DETAILS_TAB_VITALS: 'Vitals',
    W_DETAILS_TAB_AI: 'AI Insights',
    W_DETAILS_TAB_HISTORY: 'History',
    W_DETAILS_PREG_WEEK: 'Pregnancy Week',
    W_DETAILS_RISK_SUFFIX: 'Risk',
    W_DETAILS_BP: 'Blood Pressure',
    W_DETAILS_WEIGHT: 'Weight',
    W_DETAILS_PULSE: 'Pulse',
    W_DETAILS_TEMPERATURE: 'Temperature',
    W_DETAILS_HIGH_RISK_ALERT: 'High Risk Alert',
    W_DETAILS_VITALS_HEADING: 'Vitals History',
    W_DETAILS_VITALS_EMPTY: 'No vitals recorded yet',
    W_DETAILS_AI_HEADING: 'Risk Assessment',
    W_DETAILS_AI_RISK_SCORE: 'AI Risk Score',
    W_DETAILS_AI_PREECLAMPSIA_TITLE: 'Preeclampsia Flag',
    W_DETAILS_AI_PREECLAMPSIA_BODY: 'AI model has flagged potential preeclampsia risk. Immediate clinical referral recommended.',
    W_DETAILS_AI_MODEL_PREFIX: 'Model:',
    W_DETAILS_AI_MODEL_SUFFIX: 'Click "Run AI Analysis" below to get fresh prediction',
    W_DETAILS_AI_NOT_YET: 'Not yet analyzed',
    W_DETAILS_HISTORY_HEADING: 'Visit History',
    W_DETAILS_HISTORY_COMPLETE: 'Complete',
    W_DETAILS_HISTORY_EMPTY: 'No visit history',
    W_DETAILS_HISTORY_WORKER_PREFIX: 'Assigned Worker:',
    W_DETAILS_HISTORY_VILLAGE_PREFIX: 'Recorded by',
    W_DETAILS_BTN_RECORD_VITALS: 'Record Vitals',
    W_DETAILS_BTN_RUN_AI: 'Run AI Analysis',

    // ─── Worker Vitals Entry ───
    W_PAGE_TITLE_VITALS: 'Record Vitals',
    W_VITALS_HEADING: 'Vitals Input',
    W_VITALS_LABEL_PATIENT: 'Patient',
    W_VITALS_PH_PATIENT: 'Select patient…',
    W_VITALS_LABEL_SYSTOLIC: 'BP Systolic (mmHg) *',
    W_VITALS_LABEL_DIASTOLIC: 'BP Diastolic (mmHg) *',
    W_VITALS_LABEL_WEIGHT: 'Weight (kg)',
    W_VITALS_LABEL_PULSE: 'Pulse (bpm)',
    W_VITALS_LABEL_TEMP: 'Temperature (°C)',
    W_VITALS_LABEL_SYMPTOMS: 'Symptoms (comma-separated)',
    W_VITALS_PH_SYMPTOMS: 'Headache, fatigue, swelling...',
    W_VITALS_BTN_SAVE: 'Save Vitals',
    W_VITALS_BTN_SAVING: 'Saving...',
    W_VITALS_BTN_BACK: '← Back to Patient',
    W_VITALS_SUCCESS: 'Vitals saved successfully',
    W_VITALS_ERR_REQUIRED: 'Please select a patient and enter BP readings',
    W_VITALS_ERR_NETWORK: 'Connection failed. Please try again.',

    // ─── Worker AI Analysis ───
    W_PAGE_TITLE_AI: 'AI Analysis',
    W_AI_HEADING: 'AI Risk Assessment',
    W_AI_LABEL_SELECT: 'Select Patient',
    W_AI_PH_SELECT: 'Choose patient…',
    W_AI_BTN_ANALYZE: 'Run AI Analysis',
    W_AI_BTN_ANALYZING: 'Analyzing…',
    W_AI_RISK_HEADING_PREFIX: 'Risk Prediction:',
    W_AI_RISK_SCORE_LABEL: 'Risk Score',
    W_AI_PREECLAMPSIA_TITLE: 'Preeclampsia Flag',
    W_AI_PREECLAMPSIA_BODY: 'AI model has flagged potential preeclampsia risk.',
    W_AI_FACTORS_LABEL: 'Contributing Factors:',
    W_AI_MODEL_PREFIX: 'Model:',
    W_AI_SUMMARY_HEADING: 'Longitudinal Summary',
    W_AI_SUMMARY_LABEL: 'AI Assessment',
    W_AI_RECOMMENDATIONS_HEADING: 'Recommendations',
    W_AI_SOURCES_PREFIX: 'Sources:',

    // ─── Worker Alerts ───
    W_PAGE_TITLE_ALERTS: 'Alerts Center',
    W_ALERTS_ACTIVE_HEADING: 'Active Emergency SOS',
    W_ALERTS_ACTIVE_BADGE_SUFFIX: 'Active',
    W_ALERTS_LOADING: 'Loading alerts…',
    W_ALERTS_ALL_QUIET: '🎉 All quiet. No pending emergency alerts.',
    W_ALERTS_TRIGGERED_PREFIX: 'Triggered:',
    W_ALERTS_LOCATION_LABEL: '📍 Location Shared:',
    W_ALERTS_MAP_LINK: 'Open in Google Maps',
    W_ALERTS_BTN_RESOLVE: 'Mark Resolved',
    W_ALERTS_BTN_DISMISS: 'Dismiss',
    W_ALERTS_HISTORY_HEADING: 'Resolved Alerts History',
    W_ALERTS_RESOLVED_PREFIX: 'Resolved:',
    W_ALERTS_HISTORY_EMPTY: 'No history of resolved alerts.',

    // ─── Worker Sync Center ───
    W_PAGE_TITLE_SYNC: 'Sync Center',
    W_SYNC_BANNER_TITLE: 'Sync Status',
    W_SYNC_BANNER_ONLINE: 'Connected to server',
    W_SYNC_BANNER_OFFLINE: 'Offline; data will sync when connected',
    W_SYNC_BANNER_REFRESH: 'Refresh',
    W_SYNC_STAT_STATUS: 'Status',
    W_SYNC_STAT_CONFLICTS: 'Conflicts',
    W_SYNC_STATUS_ONLINE: 'Online',
    W_SYNC_STATUS_OFFLINE: 'Offline',
    W_SYNC_CONN_HEADING: 'Connection Status',
    W_SYNC_CONN_SYNCED: 'All data synced',
    W_SYNC_CONN_WAITING: 'Waiting for connection...',
    W_SYNC_CONFLICTS_HEADING_PREFIX: 'Conflicts (',
    W_SYNC_CONFLICTS_HEADING_SUFFIX: ')',
    W_SYNC_CONFLICTS_LOADING: 'Loading conflicts…',
    W_SYNC_CONFLICTS_EMPTY: 'No conflicts; all data is in sync',
    W_SYNC_DIFF_LOCAL: 'Local',
    W_SYNC_DIFF_SERVER: 'Server',
    W_SYNC_BTN_KEEP_LOCAL: 'Keep Local',
    W_SYNC_BTN_KEEP_SERVER: 'Keep Server',


    // ─── Admin Pages ───
    ADMIN_NAV_DASHBOARD: 'Dashboard',
    ADMIN_NAV_USERS: 'Users',
    ADMIN_NAV_PATIENTS: 'Patients',
    ADMIN_NAV_ANALYTICS: 'Analytics',
    ADMIN_NAV_REPORTS: 'Reports',
    ADMIN_NAV_SETTINGS: 'Settings',
    ADMIN_NAV_AICONFIG: 'AI Config',
    ADMIN_TITLE_DASHBOARD: 'Dashboard',
    ADMIN_TITLE_USERS: 'User Management',
    ADMIN_TITLE_PATIENTS: 'Patient Management',
    ADMIN_TITLE_ANALYTICS: 'AI Analytics',
    ADMIN_TITLE_REPORTS: 'Reports & Exports',
    ADMIN_TITLE_SETTINGS: 'System Settings',
    ADMIN_TITLE_AICONFIG: 'AI Engine Configuration',
    ADMIN_DASH_HELLO: 'Hello,',
    ADMIN_DASH_LOADING: 'Loading the PulseGuard system overview...',
    ADMIN_DASH_SUMMARY: 'System overview dashboard',
    ADMIN_DASH_KPI_PATIENTS: 'Total Patients',
    ADMIN_DASH_KPI_HIGH: 'High Risk Cases',
    ADMIN_DASH_KPI_MODERATE: 'Moderate Risk Cases',
    ADMIN_DASH_KPI_WORKERS: 'Active Health Workers',
    ADMIN_DASH_CHART_TRENDS: 'Maternal Risk Trends',
    ADMIN_DASH_CHART_REGION: 'Patients by Region',
    ADMIN_DASH_ALERTS: 'Real-time Alerts',
    ADMIN_DASH_ACTIVE: 'Active',
    ADMIN_USERS_SEARCH: 'Search users by name, email, phone, or role...',
    ADMIN_USERS_ADD: '+ Add User',
    ADMIN_USERS_LOADING: 'Loading users list…',
    ADMIN_USERS_COL_ID: 'User ID',
    ADMIN_USERS_COL_NAME: 'Name',
    ADMIN_USERS_COL_ROLE: 'Role',
    ADMIN_USERS_COL_EMAIL: 'Email',
    ADMIN_USERS_COL_PHONE: 'Phone',
    ADMIN_USERS_COL_CREATED: 'Created At',
    ADMIN_USERS_COL_ACTIONS: 'Actions',
    ADMIN_USERS_EMPTY: 'No users found matching the criteria.',
    ADMIN_USERS_DELETE: 'Delete',
    ADMIN_USERS_SHOWING: 'Showing',
    ADMIN_USERS_OF: 'of',
    ADMIN_USERS_WORKERS: 'Workers:',
    ADMIN_USERS_ADMINS: 'Admins:',
    ADMIN_USERS_PATIENTS: 'Patients:',
    ADMIN_USERS_MODAL_TITLE: 'Create User Account',
    ADMIN_USERS_LABEL_NAME: 'Full Name *',
    ADMIN_USERS_LABEL_EMAIL: 'Email',
    ADMIN_USERS_LABEL_PHONE: 'Phone',
    ADMIN_USERS_LABEL_PASS: 'Password *',
    ADMIN_USERS_LABEL_ROLE: 'Role *',
    ADMIN_USERS_BTN_CANCEL: 'Cancel',
    ADMIN_USERS_BTN_CREATE: 'Create User',
    ADMIN_USERS_BTN_CREATING: 'Creating...',
    ADMIN_PATIENTS_SEARCH: 'Search patients by name, village, or ID...',
    ADMIN_PATIENTS_ADD: '+ Add Patient',
    ADMIN_PATIENTS_COL_ID: 'Patient ID',
    ADMIN_PATIENTS_COL_RISK: 'Risk Level',
    ADMIN_PATIENTS_COL_WEEK: 'Week',
    ADMIN_PATIENTS_COL_WORKER: 'Assigned Worker',
    ADMIN_PATIENTS_COL_UPDATED: 'Last Updated',
    ADMIN_PATIENTS_VIEW: 'View Details',
    ADMIN_PATIENTS_EMPTY: 'No patients found matching the criteria.',
    ADMIN_PATIENTS_HIGH_RISK: 'High Risk:',
    ADMIN_PATIENTS_MODERATE: 'Moderate:',
    ADMIN_PATIENTS_LOW: 'Low:',
    ADMIN_PATIENTS_MODAL_TITLE: 'Create Patient Profile',
    ADMIN_PATIENTS_LABEL_AGE: 'Age (years)',
    ADMIN_PATIENTS_LABEL_VILLAGE: 'Village',
    ADMIN_PATIENTS_LABEL_WEEK: 'Gestational Week',
    ADMIN_ANALYTICS_REGION: 'Region',
    ADMIN_ANALYTICS_ALL_REGIONS: 'All Regions',
    ADMIN_ANALYTICS_RISK_COND: 'Risk Condition',
    ADMIN_ANALYTICS_ALL_CONDS: 'All Conditions',
    ADMIN_ANALYTICS_LOADING: 'Loading analytical datasets…',
    ADMIN_ANALYTICS_CHART_DIST: 'Risk Distribution',
    ADMIN_ANALYTICS_CHART_TREND: 'Risk Trends Over Time',
    ADMIN_ANALYTICS_PERF: 'AI Model Performance',
    ADMIN_ANALYTICS_PERF_SUB: 'XGBoost risk prediction model',
    ADMIN_ANALYTICS_ACCURACY: 'Accuracy',
    ADMIN_ANALYTICS_PRECISION: 'Precision',
    ADMIN_ANALYTICS_RECALL: 'Recall',
    ADMIN_ANALYTICS_F1: 'F1 Score',
    ADMIN_ANALYTICS_BREAKDOWN: 'Prediction Breakdown',
    ADMIN_ANALYTICS_PREECLAMPSIA: 'Preeclampsia Risk',
    ADMIN_ANALYTICS_MODERATE_CASES: 'Moderate Risk Cases',
    ADMIN_ANALYTICS_LOW_CASES: 'Low Risk Cases',
    ADMIN_ANALYTICS_CRITICAL: 'Critical',
    ADMIN_ANALYTICS_NORMAL: 'Normal',
    // ─── Admin Reports, Settings, AI Config ───
    ADMIN_REPORTS_LOADING: 'Loading reports definitions…',
    ADMIN_REPORTS_BTN_EXPORT: 'Export CSV',
    ADMIN_REPORTS_LAST_GEN: 'Last generated:',
    ADMIN_REPORTS_RPT1_TITLE: 'Maternal Health Report',
    ADMIN_REPORTS_RPT1_DESC: 'Comprehensive monthly summary of maternal health outcomes, risk distributions, and intervention effectiveness across all regions.',
    ADMIN_REPORTS_RPT2_TITLE: 'Risk Analysis Report',
    ADMIN_REPORTS_RPT2_DESC: 'AI-powered risk prediction breakdown including preeclampsia, anemia, and gestational diabetes detection rates.',
    ADMIN_REPORTS_RPT3_TITLE: 'Field Activity Report',
    ADMIN_REPORTS_RPT3_DESC: 'Health worker performance summary — visits completed, patients served, sync compliance, and response times.',
    ADMIN_REPORTS_RPT4_TITLE: 'Sync Status Report',
    ADMIN_REPORTS_RPT4_DESC: 'Offline device analytics, sync success rates, conflict resolution metrics, and data integrity audit.',
    ADMIN_REPORTS_NO_DATA: 'No patient data available to export.',
    ADMIN_SET_U_TITLE: 'User Management',
    ADMIN_SET_U_DESC: 'Manage health workers, patients, and admin accounts. Assign roles and configure permissions.',
    ADMIN_SET_U_BTN: 'Manage Users',
    ADMIN_SET_AI_TITLE: 'AI Configuration',
    ADMIN_SET_AI_DESC: 'Set risk prediction thresholds, model selection (XGBoost/Llama 3), and alert sensitivity levels.',
    ADMIN_SET_AI_BTN: 'Configure AI',
    ADMIN_SET_SYNC_TITLE: 'Offline & Sync Settings',
    ADMIN_SET_SYNC_DESC: 'Configure sync frequency, conflict resolution mode (auto-merge vs manual), and storage limits.',
    ADMIN_SET_SYNC_BTN: 'Update Settings',
    ADMIN_AI_BACK: '← Back',
    ADMIN_AI_SUBTITLE: 'Adjust risk prediction thresholds and alert sensitivity. Changes apply immediately to new vitals entries.',
    ADMIN_AI_LOADING: 'Loading AI configuration...',
    ADMIN_AI_SAVE_SUCCESS: 'AI configuration saved successfully!',
    ADMIN_AI_CARD1_TITLE: '🩺 Blood Pressure Thresholds',
    ADMIN_AI_CARD1_DESC: 'Used by the heuristic engine when the AI worker is offline. Readings above the High threshold are immediately flagged.',
    ADMIN_AI_CARD2_TITLE: '📊 Risk Score Cutoffs',
    ADMIN_AI_CARD2_DESC: 'Applied when the AI worker returns a numerical score (0.0 – 1.0). Scores above the High cutoff broadcast a real-time alert.',
    ADMIN_AI_CARD3_TITLE: '🔍 Live Threshold Preview',
    ADMIN_AI_CARD3_DESC: 'Enter a sample BP reading below to see how the active configuration would classify it.',
    ADMIN_AI_CARD4_TITLE: 'ℹ️ Threshold Decision Guide',
    ADMIN_AI_CARD4_DESC: 'How PulseGuard AI uses these configuration thresholds to safeguard patients:',
    ADMIN_AI_CARD5_TITLE: '⚙️ Configuration Controls',
    ADMIN_AI_BTN_SAVE: '💾 Save',
    ADMIN_AI_BTN_SAVING: 'Saving...',
    ADMIN_AI_BTN_RESET: 'Reset',
    ADMIN_AI_LBL_SYSTOLIC: 'Systolic',
    ADMIN_AI_LBL_DIASTOLIC: 'Diastolic',
    ADMIN_AI_RESULT: 'Result:',
    ADMIN_AI_RISK: 'Risk',
    ADMIN_AI_LOGIC: '💡 Evaluation Logic:',

  },

  'bn': {

    // ─── Language Toggle ───
    LANG_TOGGLE: 'English',

    // ─── Shared Layout (MobileLayout) ───
    LAYOUT_ONLINE: 'অনলাইন',
    LAYOUT_OFFLINE: 'অফলাইন',
    LAYOUT_SYNCING: 'সিঙ্ক হচ্ছে',
    LAYOUT_ALERTS_BTN: 'সতর্কতা',
    LAYOUT_LOGOUT_BTN: 'লগআউট',
    LAYOUT_RESPOND_BTN: 'সাড়া দিন',
    LAYOUT_PORTAL_PATIENT: 'রোগী পোর্টাল',
    LAYOUT_PORTAL_WORKER: 'মাতৃস্বাস্থ্য কর্মী পোর্টাল',
    LAYOUT_ADMIN_CONSOLE: 'অ্যাডমিন কনসোল',

    // ─── Nav Items (Patient) ───
    NAV_P_HOME: 'হোম',
    NAV_P_AICHAT: 'এআই চ্যাট',
    NAV_P_HEALTH: 'স্বাস্থ্য',
    NAV_P_ALERTS: 'সতর্কতা',
    NAV_P_PROFILE: 'প্রোফাইল',

    // ─── Nav Items (Worker) ───
    NAV_W_HOME: 'হোম',
    NAV_W_PATIENTS: 'রোগীরা',
    NAV_W_AI: 'এআই',
    NAV_W_SYNC: 'সিঙ্ক',
    NAV_W_PROFILE: 'প্রোফাইল',

    // ─── Splash ───
    SPLASH_HEADLINE: 'অফলাইন-ফার্স্ট এআই মাতৃস্বাস্থ্য সেবা',
    SPLASH_SUBLINE: 'গ্রামীণ স্বাস্থ্যকর্মী ও মায়েদের জন্য এআই-চালিত গর্ভাবস্থা ঝুঁকি পর্যবেক্ষণ, লক্ষণ পরীক্ষা এবং স্বয়ংক্রিয় ডেটা সিঙ্ক।',
    SPLASH_CTA: 'শুরু করুন →',
    SPLASH_DISCLAIMER_TITLE: 'চিকিৎসা সংক্রান্ত দাবিত্যাগ',
    SPLASH_DISCLAIMER_BODY: 'পালসগার্ড প্রশিক্ষিত স্বাস্থ্যকর্মীদের জন্য একটি সিদ্ধান্ত-সহায়তা সরঞ্জাম — এটি পেশাদার চিকিৎসা পরামর্শ, রোগনির্ণয় বা চিকিৎসার বিকল্প নয়। জরুরি পরিস্থিতিতে অবিলম্বে একজন যোগ্য স্বাস্থ্যসেবা প্রদানকারী বা নিকটতম ক্লিনিকে যোগাযোগ করুন।',

    // ─── Role Selection ───
    ROLE_HEADING: 'আপনার ভূমিকা বেছে নিন',
    ROLE_SUBHEADING: 'পালসগার্ড প্ল্যাটফর্মে কীভাবে লগইন করতে চান তা নির্বাচন করুন',
    ROLE_PATIENT_TITLE: 'রোগী / মা',
    ROLE_PATIENT_DESC: 'স্বাস্থ্য তথ্য লগ করুন, গর্ভাবস্থার ভাইটাল পরীক্ষা করুন এবং অফলাইনে এআই সহায়তা নিন।',
    ROLE_WORKER_TITLE: 'স্বাস্থ্যকর্মী',
    ROLE_WORKER_DESC: 'মায়েদের নিবন্ধন করুন, স্থানীয় ভাইটাল পর্যবেক্ষণ করুন এবং গ্রামে এআই ঝুঁকি বিশ্লেষণ দেখুন।',
    ROLE_ADMIN_TITLE: 'প্রশাসক',
    ROLE_ADMIN_DESC: 'ক্লিনিকাল অ্যাসাইনমেন্ট পরিচালনা করুন, সিস্টেম বিশ্লেষণ পরীক্ষা করুন এবং আঞ্চলিক সারসংক্ষেপ দেখুন।',
    ROLE_CONTINUE: 'চালিয়ে যান →',
    ROLE_BACK: '← স্বাগত স্ক্রিনে ফিরুন',

    // ─── Login ───
    LOGIN_HEADING: 'স্বাগতম',
    LOGIN_SUBHEADING_PREFIX: 'প্রবেশ করুন',
    LOGIN_SUBHEADING_SUFFIX: 'হিসেবে পালসগার্ড এআই-তে',
    LOGIN_LABEL_EMAIL: 'ইমেইল ঠিকানা',
    LOGIN_LABEL_PASSWORD: 'পাসওয়ার্ড',
    LOGIN_PH_EMAIL: 'আপনার@ইমেইল.com',
    LOGIN_PH_PASSWORD: '••••••••',
    LOGIN_BTN: 'সাইন ইন',
    LOGIN_BTN_LOADING: 'সাইন ইন হচ্ছে...',
    LOGIN_LINK_REGISTER: 'অ্যাকাউন্ট তৈরি করুন',
    LOGIN_LINK_CHANGE_ROLE: 'ভূমিকা পরিবর্তন করুন',
    LOGIN_ERR_PREFIX: 'ত্রুটি:',

    // ─── Register ───
    REGISTER_HEADING: 'পালসগার্ড এআই-তে যোগ দিন',
    REGISTER_SUBHEADING_PREFIX: 'আপনার',
    REGISTER_SUBHEADING_SUFFIX: 'অ্যাকাউন্ট তৈরি করুন',
    REGISTER_LABEL_NAME: 'পূর্ণ নাম *',
    REGISTER_LABEL_EMAIL: 'ইমেইল ঠিকানা *',
    REGISTER_LABEL_PHONE: 'ফোন নম্বর',
    REGISTER_LABEL_PASSWORD: 'পাসওয়ার্ড *',
    REGISTER_PH_NAME: 'ডা. সারাহ বা মায়ের নাম',
    REGISTER_PH_EMAIL: 'আপনার@ইমেইল.com',
    REGISTER_PH_PHONE: '+৮৮০ XXX XXX XXX',
    REGISTER_PH_PASSWORD: 'একটি শক্তিশালী পাসওয়ার্ড তৈরি করুন',
    REGISTER_BTN: 'অ্যাকাউন্ট তৈরি করুন',
    REGISTER_BTN_LOADING: 'অ্যাকাউন্ট তৈরি হচ্ছে...',
    REGISTER_ALREADY_HAVE: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    REGISTER_LINK_SIGNIN: 'সাইন ইন',
    REGISTER_ERR_PREFIX: 'ত্রুটি:',

    // ─── Patient Dashboard ───
    PAGE_TITLE_DASHBOARD: 'ড্যাশবোর্ড',
    DASH_LOADING: 'স্বাস্থ্য প্রোফাইল লোড হচ্ছে…',
    DASH_WELCOME_HEADING_PREFIX: 'স্বাগতম,',
    DASH_WELCOME_BODY: 'আপনার অ্যাকাউন্ট প্রস্তুত! ভাইটাল ট্র্যাকিং, এআই স্বাস্থ্য পরীক্ষা এবং ব্যক্তিগতকৃত নির্দেশনা আনলক করতে আপনার গর্ভাবস্থার প্রোফাইল সম্পন্ন করুন।',
    DASH_COMPLETE_PROFILE_BTN: '✓ আমার প্রোফাইল সম্পন্ন করুন',
    DASH_GREETING_PREFIX: 'হ্যালো,',
    DASH_WEEK_LABEL: 'গর্ভাবস্থার সপ্তাহ',
    DASH_SECTION_QUICK_ACTIONS: 'দ্রুত কার্যক্রম',
    DASH_ACTION_DAILY_TITLE: 'দৈনিক স্বাস্থ্য পরীক্ষা',
    DASH_ACTION_DAILY_DESC: 'আজকের ভাইটাল রেকর্ড করুন',
    DASH_ACTION_AI_TITLE: 'এআই লক্ষণ পরীক্ষক',
    DASH_ACTION_AI_DESC: 'পালসগার্ড এআই-এর সাথে চ্যাট করুন',
    DASH_ACTION_NUTRITION_TITLE: 'পুষ্টি পরিকল্পনা',
    DASH_ACTION_NUTRITION_DESC: 'ব্যক্তিগতকৃত খাবার গাইড',
    DASH_ACTION_EMERGENCY_TITLE: 'জরুরি এসওএস',
    DASH_ACTION_EMERGENCY_DESC: 'এক-ট্যাপ জরুরি সতর্কতা',
    DASH_SECTION_HEALTH_SUMMARY: 'স্বাস্থ্য সারসংক্ষেপ',
    DASH_KPI_BP: 'রক্তচাপ',
    DASH_KPI_WEIGHT: 'ওজন',
    DASH_KPI_TEMP: 'তাপমাত্রা',
    DASH_KPI_LAST_CHECKUP: 'শেষ পরীক্ষা',
    DASH_KPI_NO_RECORDS: 'কোনো রেকর্ড নেই',
    DASH_VIEW_ALL_RECORDS: 'সব রেকর্ড দেখুন →',

    // ─── AI Chat ───
    PAGE_TITLE_AI_CHAT: 'এআই লক্ষণ পরীক্ষক',
    AI_CHAT_PH: 'আপনার লক্ষণ বর্ণনা করুন...',
    AI_CHAT_SEND: 'পাঠান',
    AI_CHAT_ERR_OFFLINE: 'দুঃখিত, এআই সেবা বর্তমানে অফলাইন বা নাগালের বাইরে। পরে আবার চেষ্টা করুন।',
    AI_CHAT_ERR_FAILED: 'দুঃখিত, আপনার অনুরোধ প্রক্রিয়া করা সম্ভব হয়নি।',

    // ─── Daily Health Check ───
    PAGE_TITLE_DAILY_CHECK: 'দৈনিক স্বাস্থ্য পরীক্ষা',
    DAILY_LOADING: 'দৈনিক স্বাস্থ্য পরীক্ষার ফর্ম লোড হচ্ছে…',
    DAILY_NO_PROFILE_ICON: '📋',
    DAILY_NO_PROFILE_HEADING: 'প্রোফাইল সেটআপ প্রয়োজন',
    DAILY_NO_PROFILE_BODY: 'ভাইটাল রেকর্ড করার আগে আপনার গর্ভাবস্থার প্রোফাইল সম্পন্ন করতে হবে।',
    DAILY_NO_PROFILE_BTN: 'আমার প্রোফাইল সম্পন্ন করুন',
    DAILY_FORM_HEADING: 'আজকের ভাইটাল রেকর্ড করুন',
    DAILY_FORM_DATE_PREFIX: 'গর্ভাবস্থার সপ্তাহ',
    DAILY_LABEL_BP: 'রক্তচাপ (mmHg) *',
    DAILY_PH_BP: 'যেমন ১২০/৮০',
    DAILY_LABEL_WEIGHT: 'ওজন (কেজি)',
    DAILY_PH_WEIGHT: 'যেমন ৬২',
    DAILY_LABEL_TEMP: 'তাপমাত্রা (°C)',
    DAILY_PH_TEMP: 'যেমন ৩৬.৮',
    DAILY_LABEL_PULSE: 'নাড়ির গতি (bpm)',
    DAILY_PH_PULSE: 'যেমন ৭৫',
    DAILY_LABEL_SYMPTOMS: 'লক্ষণ (কমা দিয়ে আলাদা করুন)',
    DAILY_PH_SYMPTOMS: 'যেমন মাথাব্যথা, বমিভাব',
    DAILY_BTN_SAVE: 'সংরক্ষণ করুন',
    DAILY_BTN_SAVING: 'সংরক্ষণ হচ্ছে...',
    DAILY_BTN_SAVE_OFFLINE: 'অফলাইনে সংরক্ষণ করুন',
    DAILY_SUCCESS_OFFLINE: 'অফলাইন কিউতে সফলভাবে সংরক্ষিত! সংযোগ ফিরে এলে সিঙ্ক হবে।',
    DAILY_SUCCESS_PREFIX: 'দৈনিক পরীক্ষা রেকর্ড হয়েছে! ঝুঁকির অবস্থা',
    DAILY_ERR_NO_PROFILE: 'রোগীর প্রোফাইল পাওয়া যায়নি। প্রথমে নিবন্ধন সম্পন্ন করুন।',
    DAILY_ERR_BP_REQUIRED: 'রক্তচাপ প্রয়োজন (যেমন ১২০/৮০)।',
    DAILY_ERR_BP_FORMAT: 'রক্তচাপ "সিস্টোলিক/ডায়াস্টোলিক" ফরম্যাটে লিখুন (যেমন ১২০/৮০)',
    DAILY_ERR_BP_RANGE: 'অবৈধ রক্তচাপ। পরিসীমার বাইরে',
    DAILY_ERR_PULSE_RANGE: 'অবৈধ নাড়ির গতি। পরিসীমার বাইরে',
    DAILY_ERR_NETWORK: 'নেটওয়ার্ক অনুরোধ ব্যর্থ হয়েছে। অফলাইনে সংরক্ষণ করুন।',
    DAILY_ERR_SAVE_LOCAL: 'স্থানীয়ভাবে তথ্য সংরক্ষণ ব্যর্থ হয়েছে।',

    // ─── Emergency SOS ───
    PAGE_TITLE_EMERGENCY: 'জরুরি এসওএস',
    EMERGENCY_HEADING: 'জরুরি সতর্কতা',
    EMERGENCY_STATUS_READY: 'পালসগার্ড নিরাপত্তা ব্যবস্থা: প্রস্তুত',
    EMERGENCY_STATUS_SENT: 'এসওএস পাঠানো হয়েছে: সাহায্য আসছে!',
    EMERGENCY_STATUS_GPS: 'জিপিএস স্থানাঙ্ক:',
    EMERGENCY_STATUS_OFFLINE: 'অফলাইন মোড সক্রিয়',
    EMERGENCY_BODY: 'কাছের স্বাস্থ্যকর্মী ও জরুরি সেবাকে সতর্ক করতে এসওএস বোতাম চাপুন। আপনার জিপিএস অবস্থান স্বয়ংক্রিয়ভাবে শেয়ার করা হবে।',
    EMERGENCY_SOS_BTN: 'এসওএস',
    EMERGENCY_SOS_SENT: 'পাঠানো হয়েছে',
    EMERGENCY_BTN_GPS_LOADING: 'অবস্থান নেওয়া হচ্ছে…',
    EMERGENCY_BTN_GPS: 'জিপিএস অবস্থান শেয়ার করুন',
    EMERGENCY_BTN_NOTIFY: 'স্বাস্থ্যকর্মীকে জানান',
    EMERGENCY_BTN_CALL: 'জরুরি সেবায় ফোন করুন',

    // ─── Nutrition ───
    PAGE_TITLE_NUTRITION: 'পুষ্টি গাইড',
    NUTRITION_TAG_ALL: 'সব',
    NUTRITION_TAG_IRON: 'আয়রন সমৃদ্ধ',
    NUTRITION_TAG_PROTEIN: 'প্রোটিন',
    NUTRITION_TAG_CALCIUM: 'ক্যালসিয়াম',
    NUTRITION_TAG_VITAMINS: 'ভিটামিন',
    NUTRITION_SECTION_RECOMMENDED: 'প্রস্তাবিত খাবার',
    NUTRITION_SECTION_RECOMMENDED_DESC: 'গর্ভাবস্থায় প্রয়োজনীয় পুষ্টি',
    NUTRITION_SECTION_AVOID: 'যে খাবার এড়িয়ে চলবেন',
    NUTRITION_SECTION_AVOID_DESC: 'গর্ভাবস্থায় ঝুঁকি কমান',
    NUTRITION_SECTION_LOCAL: 'স্থানীয় সাশ্রয়ী খাবার',
    NUTRITION_SECTION_LOCAL_DESC: 'আপনার এলাকায় পাওয়া পুষ্টিকর বিকল্প',
    NUTRITION_EMPTY_RECOMMENDED: 'নভেম্বর/ডিসেম্বর ফিল্টারে কোনো প্রস্তাবিত খাবার নেই।',
    NUTRITION_EMPTY_LOCAL: 'নির্বাচিত ফিল্টারে কোনো স্থানীয় খাবার নেই।',

    // ─── Records ───
    PAGE_TITLE_RECORDS: 'চিকিৎসা রেকর্ড',
    RECORDS_HEADING: 'আপনার রেকর্ড',
    RECORDS_EXPORT_BTN: '⬇️ CSV রপ্তানি',
    RECORDS_LOADING: 'রেকর্ড লোড হচ্ছে…',
    RECORDS_EMPTY: 'এখনো কোনো রেকর্ড নেই।',
    RECORDS_FIELD_BP: 'রক্তচাপ:',
    RECORDS_FIELD_WEIGHT: 'ওজন:',
    RECORDS_FIELD_TEMP: 'তাপমাত্রা:',
    RECORDS_FIELD_PULSE: 'নাড়ি:',
    RECORDS_NA: 'N/A',

    // ─── Patient Alerts ───
    PAGE_TITLE_ALERTS: 'সতর্কতা',
    ALERTS_HEADING: 'বিজ্ঞপ্তি',

    // ─── Patient Profile ───
    PAGE_TITLE_PROFILE: 'প্রোফাইল',
    PROFILE_LOADING: 'প্রোফাইল বিবরণ লোড হচ্ছে…',
    PROFILE_SECTION_DETAILS: 'প্রোফাইল বিবরণ',
    PROFILE_SECTION_EDIT: 'প্রোফাইল সম্পাদনা',
    PROFILE_LABEL_PREG_WEEK: 'গর্ভাবস্থার সপ্তাহ',
    PROFILE_LABEL_RISK: 'ঝুঁকির মাত্রা',
    PROFILE_LABEL_VILLAGE: 'গ্রাম',
    PROFILE_LABEL_PHONE: 'ফোন',
    PROFILE_LABEL_EMAIL: 'ইমেইল',
    PROFILE_LABEL_ASSIGNED_PATIENTS: 'নির্ধারিত রোগী',
    PROFILE_LABEL_SYSTEM_ROLE: 'সিস্টেম ভূমিকা',
    PROFILE_LABEL_ADMIN_VALUE: 'প্রশাসক',
    PROFILE_LABEL_PROFILE_STATUS: 'প্রোফাইল অবস্থা',
    PROFILE_LABEL_PENDING: 'নিবন্ধন সম্পন্ন হওয়া বাকি',
    PROFILE_BTN_COMPLETE_REG: 'নিবন্ধন সম্পন্ন করুন',
    PROFILE_EDIT_LABEL_NAME: 'পূর্ণ নাম *',
    PROFILE_EDIT_LABEL_EMAIL: 'ইমেইল ঠিকানা',
    PROFILE_EDIT_LABEL_PHONE: 'ফোন নম্বর',
    PROFILE_EDIT_LABEL_VILLAGE: 'গ্রামের ক্লিনিক এলাকা',
    PROFILE_EDIT_LABEL_WEEK: 'গর্ভাবস্থার সপ্তাহ',
    PROFILE_EDIT_PH_NAME: 'আপনার নাম লিখুন',
    PROFILE_EDIT_PH_EMAIL: 'যেমন নাম@ডোমেইন.com',
    PROFILE_EDIT_PH_PHONE: 'যেমন +৮৮০১২৩৪৫৬৭৮৯',
    PROFILE_EDIT_PH_VILLAGE: 'যেমন গ্রাম-এ',
    PROFILE_EDIT_PH_WEEK: 'যেমন ২৪',
    PROFILE_BTN_SAVE_CHANGES: 'পরিবর্তন সংরক্ষণ করুন',
    PROFILE_BTN_SAVING: 'সংরক্ষণ হচ্ছে...',
    PROFILE_BTN_CANCEL: 'বাতিল করুন',
    PROFILE_BTN_EDIT: 'প্রোফাইল সম্পাদনা করুন',
    PROFILE_BTN_LOGOUT: 'লগআউট',
    PROFILE_ERR_NAME_REQUIRED: 'নাম আবশ্যিক',
    PROFILE_ERR_NAME_LETTERS: 'নামে শুধুমাত্র অক্ষর ও ফাঁকা স্থান থাকতে পারবে',
    PROFILE_ERR_PHONE_DIGITS: 'ফোন নম্বরে ঠিক ১১টি সংখ্যা থাকতে হবে',
    PROFILE_SUCCESS: 'প্রোফাইল সফলভাবে আপডেট হয়েছে!',
    PROFILE_PATIENT_ID_PREFIX: 'রোগী আইডি: PG-',
    PROFILE_WORKER_ID_PREFIX: 'স্বাস্থ্যকর্মী আইডি: HW-',

    // ─── Onboarding ───
    PAGE_TITLE_ONBOARDING: 'প্রোফাইল সেটআপ',
    ONBOARD_WELCOME_PREFIX: 'স্বাগতম,',
    ONBOARD_WELCOME_BODY: 'শুরু করতে, আপনার মাতৃস্বাস্থ্য প্রোফাইল সেট করতে কিছু তথ্য দরকার। এটি ভাইটাল ট্র্যাকিং, এআই স্বাস্থ্য পরীক্ষা এবং ব্যক্তিগতকৃত নির্দেশনা আনলক করবে।',
    ONBOARD_SECTION_HEADING: 'চিকিৎসা প্রোফাইল সেটআপ',
    ONBOARD_SECTION_SUBHEADING: '* চিহ্নিত সব ঘর পূরণ করা বাধ্যতামূলক।',
    ONBOARD_LABEL_WEEK: 'বর্তমান গর্ভাবস্থার সপ্তাহ *',
    ONBOARD_PH_WEEK: 'যেমন ২৪',
    ONBOARD_HINT_WEEK: '১ থেকে ৪৫-এর মধ্যে মান দিন।',
    ONBOARD_LABEL_AGE: 'আপনার বয়স',
    ONBOARD_PH_AGE: 'যেমন ২৬',
    ONBOARD_LABEL_VILLAGE: 'গ্রাম / ক্লিনিক এলাকা',
    ONBOARD_PH_VILLAGE: 'যেমন কুড়িগ্রাম গ্রাম-এ',
    ONBOARD_BTN_SUBMIT: '✓ নিবন্ধন সম্পন্ন করুন',
    ONBOARD_BTN_LOADING: 'প্রোফাইল সেটআপ হচ্ছে…',
    ONBOARD_ERR_WEEK_REQUIRED: 'আপনার বর্তমান গর্ভাবস্থার সপ্তাহ লিখুন।',
    ONBOARD_ERR_WEEK_RANGE: 'গর্ভাবস্থার সপ্তাহ ১ থেকে ৪৫-এর মধ্যে হতে হবে।',

    // ─── Worker Dashboard ───
    W_PAGE_TITLE_DASHBOARD: 'স্বাস্থ্যকর্মী',
    W_DASH_GREETING_PREFIX: 'হ্যালো,',
    W_DASH_GREETING_DEFAULT: 'স্বাস্থ্যকর্মী',
    W_DASH_LOADING: 'নির্ধারিত রোগীর তথ্য লোড হচ্ছে...',
    W_DASH_PATIENTS_SUFFIX: 'জন রোগী নির্ধারিত, যার মধ্যে',
    W_DASH_HIGH_RISK_CASE: 'জন উচ্চ ঝুঁকির রোগী আজকে।',
    W_DASH_HIGH_RISK_CASES: 'জন উচ্চ ঝুঁকির রোগী আজকে।',
    W_DASH_BANNER_TITLE: 'সিঙ্ক কেন্দ্র',
    W_DASH_BANNER_ACTION: 'সিঙ্ক খুলুন',
    W_DASH_KPI_HEADING: 'আজকের কেপিআই',
    W_DASH_KPI_TOTAL: 'মোট রোগী',
    W_DASH_KPI_HIGH: 'উচ্চ ঝুঁকির ঘটনা',
    W_DASH_KPI_MODERATE: 'মাঝারি ঝুঁকির ঘটনা',
    W_DASH_KPI_LOW: 'কম ঝুঁকির ঘটনা',
    W_DASH_SECTION_QUICK: 'দ্রুত কার্যক্রম',
    W_DASH_QUICK_PATIENTS: 'রোগীর তালিকা',
    W_DASH_QUICK_AI: 'এআই সহকারী',
    W_DASH_QUICK_SYNC: 'সিঙ্ক কেন্দ্র',
    W_DASH_SECTION_HIGH_RISK: 'উচ্চ ঝুঁকির রোগী',
    W_DASH_HIGH_RISK_SUFFIX: 'জন রোগী',
    W_DASH_LOADING_LIST: 'লোড হচ্ছে…',
    W_DASH_NO_HIGH_RISK: 'কোনো উচ্চ ঝুঁকির রোগী নেই',
    W_DASH_VIEW_BTN: 'দেখুন',
    W_DASH_SUMMARY_A: 'আপনার',
    W_DASH_SUMMARY_B: 'জন রোগী নির্ধারিত, এর মধ্যে',
    W_DASH_SUMMARY_C: 'জন উচ্চ ঝুঁকির রোগী আজকে।',

    // ─── Worker Patient List ───
    W_PAGE_TITLE_PATIENTS: 'রোগীর তালিকা',
    W_PATIENTS_SEARCH_PH: 'নাম বা গ্রাম দিয়ে রোগী খুঁজুন…',
    W_PATIENTS_FILTER_ALL: 'সব',
    W_PATIENTS_FILTER_HIGH: 'উচ্চ ঝুঁকি',
    W_PATIENTS_FILTER_MODERATE: 'মাঝারি',
    W_PATIENTS_FILTER_LOW: 'কম ঝুঁকি',
    W_PATIENTS_HEADING: 'রোগীরা',
    W_PATIENTS_RESULTS_SUFFIX: 'ফলাফল',
    W_PATIENTS_LOADING: 'রোগীর তালিকা লোড হচ্ছে…',
    W_PATIENTS_EMPTY: 'আপনার অনুসন্ধানের সাথে কোনো রোগী মিলছে না।',
    W_PATIENTS_WEEK_PREFIX: 'সপ্তাহ',
    W_PATIENTS_UNKNOWN: 'অজানা',
    W_PATIENTS_VIEW_BTN: 'দেখুন',

    // ─── Worker Patient Details ───
    W_PAGE_TITLE_PATIENT_DETAILS: 'রোগীর বিবরণ',
    W_DETAILS_LOADING: 'রোগীর তথ্য লোড হচ্ছে…',
    W_DETAILS_NOT_FOUND: 'রোগী পাওয়া যায়নি',
    W_DETAILS_AGE_PREFIX: 'বয়স:',
    W_DETAILS_WEEK_PREFIX: 'সপ্তাহ',
    W_DETAILS_TAB_OVERVIEW: 'সারসংক্ষেপ',
    W_DETAILS_TAB_VITALS: 'ভাইটাল',
    W_DETAILS_TAB_AI: 'এআই অন্তর্দৃষ্টি',
    W_DETAILS_TAB_HISTORY: 'ইতিহাস',
    W_DETAILS_PREG_WEEK: 'গর্ভাবস্থার সপ্তাহ',
    W_DETAILS_RISK_SUFFIX: 'ঝুঁকি',
    W_DETAILS_BP: 'রক্তচাপ',
    W_DETAILS_WEIGHT: 'ওজন',
    W_DETAILS_PULSE: 'নাড়ি',
    W_DETAILS_TEMPERATURE: 'তাপমাত্রা',
    W_DETAILS_HIGH_RISK_ALERT: 'উচ্চ ঝুঁকি সতর্কতা',
    W_DETAILS_VITALS_HEADING: 'ভাইটালের ইতিহাস',
    W_DETAILS_VITALS_EMPTY: 'এখনো কোনো ভাইটাল রেকর্ড নেই',
    W_DETAILS_AI_HEADING: 'ঝুঁকি মূল্যায়ন',
    W_DETAILS_AI_RISK_SCORE: 'এআই ঝুঁকি স্কোর',
    W_DETAILS_AI_PREECLAMPSIA_TITLE: 'প্রিক্ল্যাম্পসিয়া সতর্কতা',
    W_DETAILS_AI_PREECLAMPSIA_BODY: 'এআই মডেল সম্ভাব্য প্রিক্ল্যাম্পসিয়া ঝুঁকি চিহ্নিত করেছে। তাৎক্ষণিক ক্লিনিকাল রেফারেল প্রস্তাবিত।',
    W_DETAILS_AI_MODEL_PREFIX: 'মডেল:',
    W_DETAILS_AI_MODEL_SUFFIX: 'নতুন পূর্বাভাসের জন্য নিচে "এআই বিশ্লেষণ চালান" ক্লিক করুন',
    W_DETAILS_AI_NOT_YET: 'এখনো বিশ্লেষণ হয়নি',
    W_DETAILS_HISTORY_HEADING: 'পরিদর্শন ইতিহাস',
    W_DETAILS_HISTORY_COMPLETE: 'সম্পন্ন',
    W_DETAILS_HISTORY_EMPTY: 'কোনো পরিদর্শন ইতিহাস নেই',
    W_DETAILS_HISTORY_WORKER_PREFIX: 'নির্ধারিত কর্মী:',
    W_DETAILS_HISTORY_VILLAGE_PREFIX: 'রেকর্ড করেছেন',
    W_DETAILS_BTN_RECORD_VITALS: 'ভাইটাল রেকর্ড করুন',
    W_DETAILS_BTN_RUN_AI: 'এআই বিশ্লেষণ চালান',

    // ─── Worker Vitals Entry ───
    W_PAGE_TITLE_VITALS: 'ভাইটাল রেকর্ড করুন',
    W_VITALS_HEADING: 'ভাইটাল ইনপুট',
    W_VITALS_LABEL_PATIENT: 'রোগী',
    W_VITALS_PH_PATIENT: 'রোগী নির্বাচন করুন…',
    W_VITALS_LABEL_SYSTOLIC: 'সিস্টোলিক রক্তচাপ (mmHg) *',
    W_VITALS_LABEL_DIASTOLIC: 'ডায়াস্টোলিক রক্তচাপ (mmHg) *',
    W_VITALS_LABEL_WEIGHT: 'ওজন (কেজি)',
    W_VITALS_LABEL_PULSE: 'নাড়ির গতি (bpm)',
    W_VITALS_LABEL_TEMP: 'তাপমাত্রা (°C)',
    W_VITALS_LABEL_SYMPTOMS: 'লক্ষণ (কমা দিয়ে আলাদা করুন)',
    W_VITALS_PH_SYMPTOMS: 'মাথাব্যথা, ক্লান্তি, ফোলা...',
    W_VITALS_BTN_SAVE: 'ভাইটাল সংরক্ষণ করুন',
    W_VITALS_BTN_SAVING: 'সংরক্ষণ হচ্ছে...',
    W_VITALS_BTN_BACK: '← রোগীর কাছে ফিরুন',
    W_VITALS_SUCCESS: 'ভাইটাল সফলভাবে সংরক্ষিত',
    W_VITALS_ERR_REQUIRED: 'একটি রোগী নির্বাচন করুন এবং রক্তচাপ লিখুন',
    W_VITALS_ERR_NETWORK: 'সংযোগ ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',

    // ─── Worker AI Analysis ───
    W_PAGE_TITLE_AI: 'এআই বিশ্লেষণ',
    W_AI_HEADING: 'এআই ঝুঁকি মূল্যায়ন',
    W_AI_LABEL_SELECT: 'রোগী নির্বাচন করুন',
    W_AI_PH_SELECT: 'রোগী বেছে নিন…',
    W_AI_BTN_ANALYZE: 'এআই বিশ্লেষণ চালান',
    W_AI_BTN_ANALYZING: 'বিশ্লেষণ হচ্ছে…',
    W_AI_RISK_HEADING_PREFIX: 'ঝুঁকি পূর্বাভাস:',
    W_AI_RISK_SCORE_LABEL: 'ঝুঁকি স্কোর',
    W_AI_PREECLAMPSIA_TITLE: 'প্রিক্ল্যাম্পসিয়া সতর্কতা',
    W_AI_PREECLAMPSIA_BODY: 'এআই মডেল সম্ভাব্য প্রিক্ল্যাম্পসিয়া ঝুঁকি চিহ্নিত করেছে।',
    W_AI_FACTORS_LABEL: 'অবদানকারী কারণ:',
    W_AI_MODEL_PREFIX: 'মডেল:',
    W_AI_SUMMARY_HEADING: 'দীর্ঘমেয়াদী সারসংক্ষেপ',
    W_AI_SUMMARY_LABEL: 'এআই মূল্যায়ন',
    W_AI_RECOMMENDATIONS_HEADING: 'সুপারিশ',
    W_AI_SOURCES_PREFIX: 'সূত্র:',

    // ─── Worker Alerts ───
    W_PAGE_TITLE_ALERTS: 'সতর্কতা কেন্দ্র',
    W_ALERTS_ACTIVE_HEADING: 'সক্রিয় জরুরি এসওএস',
    W_ALERTS_ACTIVE_BADGE_SUFFIX: 'সক্রিয়',
    W_ALERTS_LOADING: 'সতর্কতা লোড হচ্ছে…',
    W_ALERTS_ALL_QUIET: '🎉 সব শান্ত। কোনো বিচারাধীন জরুরি সতর্কতা নেই।',
    W_ALERTS_TRIGGERED_PREFIX: 'সক্রিয় হয়েছে:',
    W_ALERTS_LOCATION_LABEL: '📍 অবস্থান শেয়ার হয়েছে:',
    W_ALERTS_MAP_LINK: 'গুগল ম্যাপে খুলুন',
    W_ALERTS_BTN_RESOLVE: 'সমাধান হয়েছে চিহ্নিত করুন',
    W_ALERTS_BTN_DISMISS: 'বাতিল করুন',
    W_ALERTS_HISTORY_HEADING: 'সমাধানকৃত সতর্কতার ইতিহাস',
    W_ALERTS_RESOLVED_PREFIX: 'সমাধান:',
    W_ALERTS_HISTORY_EMPTY: 'কোনো সমাধানকৃত সতর্কতার ইতিহাস নেই।',

    // ─── Worker Sync Center ───
    W_PAGE_TITLE_SYNC: 'সিঙ্ক কেন্দ্র',
    W_SYNC_BANNER_TITLE: 'সিঙ্ক অবস্থা',
    W_SYNC_BANNER_ONLINE: 'সার্ভারের সাথে সংযুক্ত',
    W_SYNC_BANNER_OFFLINE: 'অফলাইন; সংযোগ ফিরলে ডেটা সিঙ্ক হবে',
    W_SYNC_BANNER_REFRESH: 'রিফ্রেশ',
    W_SYNC_STAT_STATUS: 'অবস্থা',
    W_SYNC_STAT_CONFLICTS: 'দ্বন্দ্ব',
    W_SYNC_STATUS_ONLINE: 'অনলাইন',
    W_SYNC_STATUS_OFFLINE: 'অফলাইন',
    W_SYNC_CONN_HEADING: 'সংযোগ অবস্থা',
    W_SYNC_CONN_SYNCED: 'সব ডেটা সিঙ্ক হয়েছে',
    W_SYNC_CONN_WAITING: 'সংযোগের অপেক্ষায়...',
    W_SYNC_CONFLICTS_HEADING_PREFIX: 'দ্বন্দ্ব (',
    W_SYNC_CONFLICTS_HEADING_SUFFIX: ')',
    W_SYNC_CONFLICTS_LOADING: 'দ্বন্দ্ব লোড হচ্ছে…',
    W_SYNC_CONFLICTS_EMPTY: 'কোনো দ্বন্দ্ব নেই; সব ডেটা সিঙ্কে আছে',
    W_SYNC_DIFF_LOCAL: 'স্থানীয়',
    W_SYNC_DIFF_SERVER: 'সার্ভার',
    W_SYNC_BTN_KEEP_LOCAL: 'স্থানীয় রাখুন',
    W_SYNC_BTN_KEEP_SERVER: 'সার্ভার রাখুন',


    // ─── Admin Pages ───
    ADMIN_NAV_DASHBOARD: 'ড্যাশবোর্ড',
    ADMIN_NAV_USERS: 'ব্যবহারকারী',
    ADMIN_NAV_PATIENTS: 'রোগী',
    ADMIN_NAV_ANALYTICS: 'বিশ্লেষণ',
    ADMIN_NAV_REPORTS: 'রিপোর্ট',
    ADMIN_NAV_SETTINGS: 'সেটিংস',
    ADMIN_NAV_AICONFIG: 'এআই কনফিগারেশন',
    ADMIN_TITLE_DASHBOARD: 'ড্যাশবোর্ড',
    ADMIN_TITLE_USERS: 'ব্যবহারকারী ব্যবস্থাপনা',
    ADMIN_TITLE_PATIENTS: 'রোগী ব্যবস্থাপনা',
    ADMIN_TITLE_ANALYTICS: 'এআই বিশ্লেষণ',
    ADMIN_TITLE_REPORTS: 'রিপোর্ট ও এক্সপোর্ট',
    ADMIN_TITLE_SETTINGS: 'সিস্টেম সেটিংস',
    ADMIN_TITLE_AICONFIG: 'এআই ইঞ্জিন কনফিগারেশন',
    ADMIN_DASH_HELLO: 'হ্যালো,',
    ADMIN_DASH_LOADING: 'সিস্টেম ওভারভিউ লোড হচ্ছে...',
    ADMIN_DASH_SUMMARY: 'সিস্টেম ওভারভিউ ড্যাশবোর্ড',
    ADMIN_DASH_KPI_PATIENTS: 'মোট রোগী',
    ADMIN_DASH_KPI_HIGH: 'উচ্চ ঝুঁকির ঘটনা',
    ADMIN_DASH_KPI_MODERATE: 'মাঝারি ঝুঁকির ঘটনা',
    ADMIN_DASH_KPI_WORKERS: 'সক্রিয় স্বাস্থ্যকর্মী',
    ADMIN_DASH_CHART_TRENDS: 'মাতৃমৃত্যু ঝুঁকির প্রবণতা',
    ADMIN_DASH_CHART_REGION: 'অঞ্চল অনুযায়ী রোগী',
    ADMIN_DASH_ALERTS: 'রিয়েল-টাইম সতর্কতা',
    ADMIN_DASH_ACTIVE: 'সক্রিয়',
    ADMIN_USERS_SEARCH: 'নাম, ইমেইল বা ভূমিকা দ্বারা খুঁজুন...',
    ADMIN_USERS_ADD: '+ ব্যবহারকারী যোগ করুন',
    ADMIN_USERS_LOADING: 'ব্যবহারকারী তালিকা লোড হচ্ছে…',
    ADMIN_USERS_COL_ID: 'ব্যবহারকারী আইডি',
    ADMIN_USERS_COL_NAME: 'নাম',
    ADMIN_USERS_COL_ROLE: 'ভূমিকা',
    ADMIN_USERS_COL_EMAIL: 'ইমেইল',
    ADMIN_USERS_COL_PHONE: 'ফোন',
    ADMIN_USERS_COL_CREATED: 'তৈরি হয়েছে',
    ADMIN_USERS_COL_ACTIONS: 'কার্যক্রম',
    ADMIN_USERS_EMPTY: 'কোনো ব্যবহারকারী পাওয়া যায়নি।',
    ADMIN_USERS_DELETE: 'মুছুন',
    ADMIN_USERS_SHOWING: 'দেখাচ্ছে',
    ADMIN_USERS_OF: 'এর মধ্যে',
    ADMIN_USERS_WORKERS: 'কর্মী:',
    ADMIN_USERS_ADMINS: 'প্রশাসক:',
    ADMIN_USERS_PATIENTS: 'রোগী:',
    ADMIN_USERS_MODAL_TITLE: 'ব্যবহারকারী অ্যাকাউন্ট তৈরি করুন',
    ADMIN_USERS_LABEL_NAME: 'পূর্ণ নাম *',
    ADMIN_USERS_LABEL_EMAIL: 'ইমেইল',
    ADMIN_USERS_LABEL_PHONE: 'ফোন',
    ADMIN_USERS_LABEL_PASS: 'পাসওয়ার্ড *',
    ADMIN_USERS_LABEL_ROLE: 'ভূমিকা *',
    ADMIN_USERS_BTN_CANCEL: 'বাতিল',
    ADMIN_USERS_BTN_CREATE: 'অ্যাকাউন্ট তৈরি করুন',
    ADMIN_USERS_BTN_CREATING: 'তৈরি হচ্ছে...',
    ADMIN_PATIENTS_SEARCH: 'নাম, গ্রাম বা আইডি দিয়ে খুঁজুন...',
    ADMIN_PATIENTS_ADD: '+ রোগী যোগ করুন',
    ADMIN_PATIENTS_COL_ID: 'রোগী আইডি',
    ADMIN_PATIENTS_COL_RISK: 'ঝুঁকির মাত্রা',
    ADMIN_PATIENTS_COL_WEEK: 'সপ্তাহ',
    ADMIN_PATIENTS_COL_WORKER: 'নির্ধারিত কর্মী',
    ADMIN_PATIENTS_COL_UPDATED: 'শেষ আপডেট',
    ADMIN_PATIENTS_VIEW: 'বিবরণ দেখুন',
    ADMIN_PATIENTS_EMPTY: 'কোনো রোগী পাওয়া যায়নি।',
    ADMIN_PATIENTS_HIGH_RISK: 'উচ্চ ঝুঁকি:',
    ADMIN_PATIENTS_MODERATE: 'মাঝারি:',
    ADMIN_PATIENTS_LOW: 'কম ঝুঁকি:',
    ADMIN_PATIENTS_MODAL_TITLE: 'রোগীর প্রোফাইল তৈরি করুন',
    ADMIN_PATIENTS_LABEL_AGE: 'বয়স',
    ADMIN_PATIENTS_LABEL_VILLAGE: 'গ্রাম',
    ADMIN_PATIENTS_LABEL_WEEK: 'গর্ভাবস্থার সপ্তাহ',
    ADMIN_ANALYTICS_REGION: 'অঞ্চল',
    ADMIN_ANALYTICS_ALL_REGIONS: 'সব অঞ্চল',
    ADMIN_ANALYTICS_RISK_COND: 'ঝুঁকির অবস্থা',
    ADMIN_ANALYTICS_ALL_CONDS: 'সব অবস্থা',
    ADMIN_ANALYTICS_LOADING: 'অ্যানালিটিক্স লোড হচ্ছে…',
    ADMIN_ANALYTICS_CHART_DIST: 'ঝুঁকি বিতরণ',
    ADMIN_ANALYTICS_CHART_TREND: 'সময়ের সাথে ঝুঁকির প্রবণতা',
    ADMIN_ANALYTICS_PERF: 'এআই মডেলের কর্মক্ষমতা',
    ADMIN_ANALYTICS_PERF_SUB: 'এক্সজি-বুস্ট ঝুঁকি পূর্বাভাস মডেল',
    ADMIN_ANALYTICS_ACCURACY: 'সঠিকতা (Accuracy)',
    ADMIN_ANALYTICS_PRECISION: 'যথাযথতা (Precision)',
    ADMIN_ANALYTICS_RECALL: 'রিকল (Recall)',
    ADMIN_ANALYTICS_F1: 'এফ-ওয়ান স্কোর (F1 Score)',
    ADMIN_ANALYTICS_BREAKDOWN: 'পূর্বাভাস বিভাজন',
    ADMIN_ANALYTICS_PREECLAMPSIA: 'প্রিক্ল্যাম্পসিয়া ঝুঁকি',
    ADMIN_ANALYTICS_MODERATE_CASES: 'মাঝারি ঝুঁকির ঘটনা',
    ADMIN_ANALYTICS_LOW_CASES: 'কম ঝুঁকির ঘটনা',
    ADMIN_ANALYTICS_CRITICAL: 'সংকটাপন্ন',
    ADMIN_ANALYTICS_NORMAL: 'স্বাভাবিক',
    // ─── Admin Reports, Settings, AI Config ───
    ADMIN_REPORTS_LOADING: 'রিপোর্ট সংজ্ঞা লোড হচ্ছে…',
    ADMIN_REPORTS_BTN_EXPORT: 'CSV এক্সপোর্ট করুন',
    ADMIN_REPORTS_LAST_GEN: 'শেষ জেনারেট হয়েছে:',
    ADMIN_REPORTS_RPT1_TITLE: 'মাতৃস্বাস্থ্য রিপোর্ট',
    ADMIN_REPORTS_RPT1_DESC: 'সব অঞ্চলের মাতৃস্বাস্থ্যের ফলাফল, ঝুঁকি বিতরণ এবং হস্তক্ষেপের কার্যকারিতার মাসিক সারসংক্ষেপ।',
    ADMIN_REPORTS_RPT2_TITLE: 'ঝুঁকি বিশ্লেষণ রিপোর্ট',
    ADMIN_REPORTS_RPT2_DESC: 'প্রিক্ল্যাম্পসিয়া, অ্যানিমিয়া এবং গর্ভাবস্থার ডায়াবেটিস শনাক্তকরণ হার সহ এআই-ভিত্তিক ঝুঁকি পূর্বাভাসের বিভাজন।',
    ADMIN_REPORTS_RPT3_TITLE: 'মাঠ পর্যায়ের কার্যক্রম রিপোর্ট',
    ADMIN_REPORTS_RPT3_DESC: 'স্বাস্থ্যকর্মীর পারফরম্যান্সের সারসংক্ষেপ — পরিদর্শন, সেবা দেওয়া রোগীর সংখ্যা, সিঙ্ক কমপ্লায়েন্স এবং রেসপন্স টাইম।',
    ADMIN_REPORTS_RPT4_TITLE: 'সিঙ্ক স্ট্যাটাস রিপোর্ট',
    ADMIN_REPORTS_RPT4_DESC: 'অফলাইন ডিভাইস অ্যানালিটিক্স, সিঙ্ক সাফল্যের হার, দ্বন্দ্ব সমাধানের মেট্রিক্স এবং ডেটা অখণ্ডতা অডিট।',
    ADMIN_REPORTS_NO_DATA: 'এক্সপোর্ট করার মতো কোনো রোগীর ডেটা নেই।',
    ADMIN_SET_U_TITLE: 'ব্যবহারকারী ব্যবস্থাপনা',
    ADMIN_SET_U_DESC: 'স্বাস্থ্যকর্মী, রোগী এবং অ্যাডমিন অ্যাকাউন্ট পরিচালনা করুন। ভূমিকা ও অনুমতি সেট করুন।',
    ADMIN_SET_U_BTN: 'ব্যবহারকারী পরিচালনা করুন',
    ADMIN_SET_AI_TITLE: 'এআই কনফিগারেশন',
    ADMIN_SET_AI_DESC: 'ঝুঁকি পূর্বাভাসের থ্রেশহোল্ড, মডেল নির্বাচন (XGBoost/Llama 3) এবং সতর্কতা সংবেদনশীলতা সেট করুন।',
    ADMIN_SET_AI_BTN: 'এআই কনফিগার করুন',
    ADMIN_SET_SYNC_TITLE: 'অফলাইন ও সিঙ্ক সেটিংস',
    ADMIN_SET_SYNC_DESC: 'সিঙ্ক ফ্রিকোয়েন্সি, দ্বন্দ্ব সমাধান মোড এবং স্টোরেজ সীমা কনফিগার করুন।',
    ADMIN_SET_SYNC_BTN: 'সেটিংস আপডেট করুন',
    ADMIN_AI_BACK: '← ফিরে যান',
    ADMIN_AI_SUBTITLE: 'ঝুঁকি পূর্বাভাসের থ্রেশহোল্ড এবং সতর্কতা সংবেদনশীলতা সামঞ্জস্য করুন।',
    ADMIN_AI_LOADING: 'এআই কনফিগারেশন লোড হচ্ছে...',
    ADMIN_AI_SAVE_SUCCESS: 'এআই কনফিগারেশন সফলভাবে সংরক্ষিত হয়েছে!',
    ADMIN_AI_CARD1_TITLE: '🩺 রক্তচাপ থ্রেশহোল্ড',
    ADMIN_AI_CARD1_DESC: 'অফলাইনে হিউরিস্টিক ইঞ্জিন দ্বারা ব্যবহৃত হয়। উচ্চ থ্রেশহোল্ডের উপরের রিডিং ফ্ল্যাগ করা হয়।',
    ADMIN_AI_CARD2_TITLE: '📊 ঝুঁকি স্কোর কাটঅফ',
    ADMIN_AI_CARD2_DESC: 'এআই কর্মী যখন একটি স্কোর (0.0 - 1.0) দেয় তখন প্রয়োগ করা হয়।',
    ADMIN_AI_CARD3_TITLE: '🔍 লাইভ থ্রেশহোল্ড প্রিভিউ',
    ADMIN_AI_CARD3_DESC: 'সক্রিয় কনফিগারেশন কীভাবে রিডিং মূল্যায়ন করবে তা দেখতে নিচে রক্তচাপ লিখুন।',
    ADMIN_AI_CARD4_TITLE: 'ℹ️ থ্রেশহোল্ড সিদ্ধান্ত গাইড',
    ADMIN_AI_CARD4_DESC: 'কীভাবে পালসগার্ড এআই এই থ্রেশহোল্ড ব্যবহার করে:',
    ADMIN_AI_CARD5_TITLE: '⚙️ কনফিগারেশন কন্ট্রোল',
    ADMIN_AI_BTN_SAVE: '💾 সংরক্ষণ করুন',
    ADMIN_AI_BTN_SAVING: 'সংরক্ষণ হচ্ছে...',
    ADMIN_AI_BTN_RESET: 'রিসেট',
    ADMIN_AI_LBL_SYSTOLIC: 'সিস্টোলিক',
    ADMIN_AI_LBL_DIASTOLIC: 'ডায়াস্টোলিক',
    ADMIN_AI_RESULT: 'ফলাফল:',
    ADMIN_AI_RISK: 'ঝুঁকি',
    ADMIN_AI_LOGIC: '💡 মূল্যায়নের যুক্তি:',
  }
}

const $ = (item, locale = 'en') => {
  return strings[locale]?.[item] ?? strings['en'][item] ?? item
}

export default $