// ═══════════════════════════════════════════════════════════
// PulseGuard AI – Internationalization Strings (EN ↔ BN)
// ═══════════════════════════════════════════════════════════

const strings = {

  // ── Common / Shared ──────────────────────────────────────
  BRAND_NAME:                     { en: 'PulseGuard',                              bn: 'পালসগার্ড' },
  ALT_LOGO:                       { en: 'logo',                                    bn: 'লোগো' },
  LOADING:                        { en: 'Loading…',                                bn: 'লোড হচ্ছে…' },
  ERROR_PREFIX:                   { en: 'Error:',                                  bn: 'ত্রুটি:' },
  ERROR_CONNECTION_FAILED:        { en: 'Connection failed. Please try again.',    bn: 'সংযোগ ব্যর্থ হয়েছে। আবার চেষ্টা করুন।' },
  FALLBACK_NA:                    { en: 'N/A',                                     bn: 'প্রযোজ্য নয়' },
  JUST_NOW:                       { en: 'Just now',                                bn: 'এইমাত্র' },
  CANCEL:                         { en: 'Cancel',                                  bn: 'বাতিল' },
  SAVE:                           { en: 'Save',                                    bn: 'সেভ করুন' },
  DELETE:                         { en: 'Delete',                                  bn: 'মুছুন' },
  VIEW:                           { en: 'View',                                    bn: 'দেখুন' },
  UNKNOWN:                        { en: 'Unknown',                                 bn: 'অজানা' },
  WEEK:                           { en: 'Week',                                    bn: 'সপ্তাহ' },
  ONLINE:                         { en: 'Online',                                  bn: 'অনলাইন' },
  OFFLINE:                        { en: 'Offline',                                 bn: 'অফলাইন' },
  SYNCING:                        { en: 'Syncing',                                 bn: 'সিঙ্ক হচ্ছে' },
  ALERTS:                         { en: 'Alerts',                                  bn: 'সতর্কতা' },
  LOGOUT:                         { en: 'Logout',                                  bn: 'লগআউট' },
  RESPOND:                        { en: 'Respond',                                 bn: 'সাড়া দিন' },
  STATUS:                         { en: 'Status',                                  bn: 'অবস্থা' },

  // ── Risk Levels ──────────────────────────────────────────
  RISK_HIGH:                      { en: 'High',                                    bn: 'উচ্চ' },
  RISK_MODERATE:                  { en: 'Moderate',                                bn: 'মাঝারি' },
  RISK_LOW:                       { en: 'Low',                                     bn: 'নিম্ন' },
  RISK_SUFFIX:                    { en: 'Risk',                                    bn: 'ঝুঁকি' },
  HIGH_RISK:                      { en: 'High Risk',                               bn: 'উচ্চ ঝুঁকি' },
  MODERATE_RISK:                  { en: 'Moderate Risk',                           bn: 'মাঝারি ঝুঁকি' },
  LOW_RISK:                       { en: 'Low Risk',                                bn: 'নিম্ন ঝুঁকি' },

  // ── Role Labels ──────────────────────────────────────────
  ROLE_PATIENT:                   { en: 'Patient / Mother',                        bn: 'রোগী / মা' },
  ROLE_WORKER:                    { en: 'Health Worker',                           bn: 'স্বাস্থ্যকর্মী' },
  ROLE_ADMIN:                     { en: 'Administrator',                           bn: 'প্রশাসক' },
  ROLE_DEFAULT:                   { en: 'User',                                    bn: 'ব্যবহারকারী' },
  ROLE_GUEST:                     { en: 'Guest',                                   bn: 'অতিথি' },

  // ── Navigation Labels ────────────────────────────────────
  NAV_HOME:                       { en: 'Home',                                    bn: 'হোম' },
  NAV_AI_CHAT:                    { en: 'AI Chat',                                 bn: 'এআই চ্যাট' },
  NAV_HEALTH:                     { en: 'Health',                                  bn: 'স্বাস্থ্য' },
  NAV_ALERTS:                     { en: 'Alerts',                                  bn: 'সতর্কতা' },
  NAV_PROFILE:                    { en: 'Profile',                                 bn: 'প্রোফাইল' },
  NAV_PATIENTS:                   { en: 'Patients',                                bn: 'রোগীরা' },
  NAV_AI:                         { en: 'AI',                                      bn: 'এআই' },
  NAV_SYNC:                       { en: 'Sync',                                    bn: 'সিঙ্ক' },

  // ── Admin Sidebar ────────────────────────────────────────
  SIDEBAR_DASHBOARD:              { en: 'Dashboard',                               bn: 'ড্যাশবোর্ড' },
  SIDEBAR_USERS:                  { en: 'Users',                                   bn: 'ব্যবহারকারী' },
  SIDEBAR_PATIENTS:               { en: 'Patients',                                bn: 'রোগীরা' },
  SIDEBAR_ANALYTICS:              { en: 'Analytics',                               bn: 'বিশ্লেষণ' },
  SIDEBAR_REPORTS:                { en: 'Reports',                                 bn: 'রিপোর্ট' },
  SIDEBAR_SETTINGS:               { en: 'Settings',                                bn: 'সেটিংস' },

  // ── Splash Page ──────────────────────────────────────────
  SPLASH_HEADING:                 { en: 'Offline-First AI Maternal Healthcare',    bn: 'অফলাইন-ফার্স্ট এআই মাতৃস্বাস্থ্য সেবা' },
  SPLASH_DESCRIPTION:             { en: 'AI-powered pregnancy risk monitoring, symptom checking, and automatic database syncing for rural health workers and mothers.', bn: 'এআই-চালিত গর্ভাবস্থার ঝুঁকি পর্যবেক্ষণ, উপসর্গ পরীক্ষা এবং গ্রামীণ স্বাস্থ্যকর্মী ও মায়েদের জন্য স্বয়ংক্রিয় ডেটাবেস সিঙ্কিং।' },
  SPLASH_CTA:                    { en: 'Get Started →',                            bn: 'শুরু করুন →' },
  SPLASH_COPYRIGHT:              { en: '© {year} PulseGuard AI. All rights reserved.', bn: '© {year} পালসগার্ড এআই। সর্বস্বত্ব সংরক্ষিত।' },
  ALT_ONBOARDING_IMAGE:          { en: 'Healthcare Onboarding Illustration',       bn: 'স্বাস্থ্যসেবা অনবোর্ডিং চিত্র' },
  ALT_HEALTHCARE_ILLUSTRATION:   { en: 'Healthcare Illustration',                  bn: 'স্বাস্থ্যসেবা চিত্র' },

  // ── Role Selection ───────────────────────────────────────
  ROLE_SELECTION_HEADING:         { en: 'Choose Your Role',                        bn: 'আপনার ভূমিকা নির্বাচন করুন' },
  ROLE_SELECTION_SUBHEADING:      { en: 'Select how you want to log in to the PulseGuard platform', bn: 'পালসগার্ড প্ল্যাটফর্মে কিভাবে লগইন করতে চান তা নির্বাচন করুন' },
  ROLE_DESC_PATIENT:             { en: 'Log health data, check pregnancy vitals, and consult the AI assistant offline.', bn: 'স্বাস্থ্য তথ্য লিপিবদ্ধ করুন, গর্ভাবস্থার ভাইটাল পরীক্ষা করুন এবং অফলাইনে এআই সহকারীর পরামর্শ নিন।' },
  ROLE_DESC_WORKER:              { en: 'Register mothers, monitor local vitals, and review AI risk analysis in villages.', bn: 'মায়েদের নিবন্ধন করুন, স্থানীয় ভাইটাল পর্যবেক্ষণ করুন এবং গ্রামে এআই ঝুঁকি বিশ্লেষণ পর্যালোচনা করুন।' },
  ROLE_DESC_ADMIN:               { en: 'Manage clinical assignments, inspect system analytics, and view regional summaries.', bn: 'ক্লিনিক্যাল অ্যাসাইনমেন্ট পরিচালনা করুন, সিস্টেম বিশ্লেষণ পরিদর্শন করুন এবং আঞ্চলিক সারসংক্ষেপ দেখুন।' },
  ROLE_CARD_CTA:                 { en: 'Continue →',                               bn: 'এগিয়ে যান →' },
  BACK_TO_WELCOME:               { en: '← Back to Welcome Screen',                bn: '← স্বাগত স্ক্রিনে ফিরে যান' },

  // ── Login Page ───────────────────────────────────────────
  LOGIN_HEADING:                  { en: 'Welcome Back',                            bn: 'স্বাগতম' },
  LOGIN_SUBHEADING:               { en: 'Sign in as {role} to access PulseGuard AI', bn: '{role} হিসেবে পালসগার্ড এআই-তে সাইন ইন করুন' },
  LOGIN_ERROR_EMPTY_FIELDS:       { en: 'Please enter email and password',         bn: 'অনুগ্রহ করে ইমেইল এবং পাসওয়ার্ড দিন' },
  LOGIN_ERROR_INVALID:            { en: 'Invalid email or password',               bn: 'ভুল ইমেইল বা পাসওয়ার্ড' },
  LABEL_EMAIL:                    { en: 'Email Address',                           bn: 'ইমেইল ঠিকানা' },
  ALT_EMAIL_ICON:                 { en: 'email',                                   bn: 'ইমেইল' },
  PLACEHOLDER_EMAIL:              { en: 'you@example.com',                         bn: 'you@example.com' },
  LABEL_PASSWORD:                 { en: 'Password',                                bn: 'পাসওয়ার্ড' },
  PLACEHOLDER_PASSWORD:           { en: '••••••••',                                bn: '••••••••' },
  LOGIN_BTN_SUBMITTING:           { en: 'Signing in...',                           bn: 'সাইন ইন হচ্ছে...' },
  LOGIN_BTN:                      { en: 'Sign In',                                 bn: 'সাইন ইন' },
  LINK_CREATE_ACCOUNT:            { en: 'Create an Account',                       bn: 'অ্যাকাউন্ট তৈরি করুন' },
  LINK_CHANGE_ROLE:               { en: 'Change Role',                             bn: 'ভূমিকা পরিবর্তন করুন' },

  // ── Register Page ────────────────────────────────────────
  REGISTER_HEADING:               { en: 'Join PulseGuard AI',                      bn: 'পালসগার্ড এআই-তে যোগ দিন' },
  REGISTER_SUBHEADING:            { en: 'Create your {role} account to get started', bn: 'শুরু করতে আপনার {role} অ্যাকাউন্ট তৈরি করুন' },
  REGISTER_ERROR_REQUIRED:        { en: 'Please fill in all required fields',      bn: 'অনুগ্রহ করে সকল প্রয়োজনীয় ক্ষেত্র পূরণ করুন' },
  REGISTER_ERROR_FAILED:          { en: 'Registration failed',                     bn: 'নিবন্ধন ব্যর্থ হয়েছে' },
  LABEL_FULL_NAME:                { en: 'Full Name *',                             bn: 'পূর্ণ নাম *' },
  ALT_USER_ICON:                  { en: 'user',                                    bn: 'ব্যবহারকারী' },
  PLACEHOLDER_FULL_NAME:          { en: "Dr. Sarah Connor or Mother's Name",       bn: 'ডাঃ সারাহ কনর বা মায়ের নাম' },
  LABEL_EMAIL_REQUIRED:           { en: 'Email Address *',                         bn: 'ইমেইল ঠিকানা *' },
  LABEL_PHONE:                    { en: 'Phone Number',                            bn: 'ফোন নম্বর' },
  ALT_PHONE_ICON:                 { en: 'phone',                                   bn: 'ফোন' },
  PLACEHOLDER_PHONE:              { en: '+880 XXX XXX XXX',                        bn: '+880 XXX XXX XXX' },
  LABEL_PASSWORD_REQUIRED:        { en: 'Password *',                              bn: 'পাসওয়ার্ড *' },
  PLACEHOLDER_PASSWORD_CREATE:    { en: 'Create a strong password',                bn: 'একটি শক্তিশালী পাসওয়ার্ড তৈরি করুন' },
  REGISTER_BTN_SUBMITTING:        { en: 'Creating Account...',                     bn: 'অ্যাকাউন্ট তৈরি হচ্ছে...' },
  REGISTER_BTN:                   { en: 'Create Account',                          bn: 'অ্যাকাউন্ট তৈরি করুন' },
  REGISTER_EXISTING_ACCOUNT:      { en: 'Already have an account?',                bn: 'ইতিমধ্যে অ্যাকাউন্ট আছে?' },
  LINK_SIGN_IN:                   { en: 'Sign In',                                 bn: 'সাইন ইন' },

  // ── Patient Dashboard ────────────────────────────────────
  DASHBOARD:                      { en: 'Dashboard',                               bn: 'ড্যাশবোর্ড' },
  DASHBOARD_LOADING:              { en: 'Loading health profile…',                 bn: 'স্বাস্থ্য প্রোফাইল লোড হচ্ছে…' },
  DASHBOARD_WELCOME:              { en: 'Welcome, {name}!',                        bn: 'স্বাগতম, {name}!' },
  DASHBOARD_WELCOME_FALLBACK:     { en: 'Mother',                                  bn: 'মা' },
  DASHBOARD_WELCOME_DESC:         { en: 'Your account is ready! Complete your pregnancy profile to unlock vitals tracking, AI health checks, and personalised guidance.', bn: 'আপনার অ্যাকাউন্ট প্রস্তুত! ভাইটাল ট্র্যাকিং, এআই স্বাস্থ্য পরীক্ষা এবং ব্যক্তিগত নির্দেশনা আনলক করতে আপনার গর্ভাবস্থার প্রোফাইল সম্পূর্ণ করুন।' },
  DASHBOARD_COMPLETE_PROFILE:     { en: '✓ Complete My Profile',                   bn: '✓ আমার প্রোফাইল সম্পূর্ণ করুন' },
  DASHBOARD_HELLO:                { en: 'Hello, {name}',                           bn: 'হ্যালো, {name}' },
  DASHBOARD_PREGNANCY_WEEK:       { en: 'Pregnancy Week',                          bn: 'গর্ভাবস্থার সপ্তাহ' },
  DASHBOARD_QUICK_ACTIONS:        { en: 'Quick Actions',                           bn: 'দ্রুত কার্যক্রম' },
  DASHBOARD_ACTION_DAILY_CHECK:   { en: 'Daily Health Check',                      bn: 'দৈনিক স্বাস্থ্য পরীক্ষা' },
  DASHBOARD_ACTION_DAILY_DESC:    { en: "Record today's vitals",                   bn: 'আজকের ভাইটাল রেকর্ড করুন' },
  DASHBOARD_ACTION_AI_CHAT:       { en: 'AI Symptom Checker',                      bn: 'এআই সিম্পটম চেকার' },
  DASHBOARD_ACTION_AI_DESC:       { en: 'Chat with PulseGuard AI',                 bn: 'পালসগার্ড এআই-এর সাথে চ্যাট করুন' },
  DASHBOARD_ACTION_NUTRITION:     { en: 'Nutrition Plan',                           bn: 'পুষ্টি পরিকল্পনা' },
  DASHBOARD_ACTION_NUTRITION_DESC: { en: 'Personalized meal guide',                bn: 'ব্যক্তিগত খাদ্য নির্দেশিকা' },
  DASHBOARD_ACTION_EMERGENCY:     { en: 'Emergency SOS',                           bn: 'জরুরি এসওএস' },
  DASHBOARD_ACTION_EMERGENCY_DESC: { en: 'One-tap emergency alert',               bn: 'এক-ট্যাপ জরুরি সতর্কতা' },
  DASHBOARD_HEALTH_SUMMARY:       { en: 'Health Summary',                          bn: 'স্বাস্থ্য সারসংক্ষেপ' },
  DASHBOARD_KPI_BP:               { en: 'Blood Pressure',                          bn: 'রক্তচাপ' },
  DASHBOARD_KPI_WEIGHT:           { en: 'Weight',                                  bn: 'ওজন' },
  DASHBOARD_KPI_TEMPERATURE:      { en: 'Temperature',                             bn: 'তাপমাত্রা' },
  DASHBOARD_KPI_LAST_CHECKUP:     { en: 'Last Checkup',                            bn: 'শেষ চেকআপ' },
  DASHBOARD_KPI_NO_RECORDS:       { en: 'No records',                              bn: 'কোনো রেকর্ড নেই' },
  DASHBOARD_VIEW_ALL_RECORDS:     { en: 'View All Records →',                      bn: 'সকল রেকর্ড দেখুন →' },

  // ── AI Chat ──────────────────────────────────────────────
  AI_SYMPTOM_CHECKER:             { en: 'AI Symptom Checker',                      bn: 'এআই সিম্পটম চেকার' },
  AICHAT_CHIP_HEADACHE:           { en: 'Headache',                                bn: 'মাথাব্যথা' },
  AICHAT_CHIP_FEVER:              { en: 'Fever',                                   bn: 'জ্বর' },
  AICHAT_CHIP_DIZZINESS:          { en: 'Dizziness',                               bn: 'মাথা ঘোরা' },
  AICHAT_CHIP_NAUSEA:             { en: 'Nausea',                                  bn: 'বমি ভাব' },
  AICHAT_CHIP_SWELLING:           { en: 'Swelling',                                bn: 'ফোলাভাব' },
  AICHAT_FALLBACK_RESPONSE:       { en: "Sorry, I couldn't process that request.", bn: 'দুঃখিত, আমি সেই অনুরোধটি প্রক্রিয়া করতে পারিনি।' },
  AICHAT_SERVICE_OFFLINE:         { en: 'Sorry, the AI service is currently offline or unreachable. Please try again later.', bn: 'দুঃখিত, এআই সেবাটি বর্তমানে অফলাইন বা অনুপলব্ধ। অনুগ্রহ করে পরে আবার চেষ্টা করুন।' },
  AICHAT_INPUT_PLACEHOLDER:       { en: 'Describe your symptoms...',               bn: 'আপনার উপসর্গ বর্ণনা করুন...' },
  AICHAT_VOICE_INPUT:             { en: 'Voice input',                             bn: 'ভয়েস ইনপুট' },
  AICHAT_SEND:                    { en: 'Send',                                    bn: 'পাঠান' },

  // ── Daily Health Check ───────────────────────────────────
  DAILY_PAGE_TITLE:               { en: 'Daily Health Check',                      bn: 'দৈনিক স্বাস্থ্য পরীক্ষা' },
  DAILY_LOADING:                  { en: 'Loading daily health check form…',        bn: 'দৈনিক স্বাস্থ্য পরীক্ষা ফর্ম লোড হচ্ছে…' },
  DAILY_ERROR_NO_PATIENT:         { en: 'No patient profile found. Please register first.', bn: 'কোনো রোগীর প্রোফাইল পাওয়া যায়নি। অনুগ্রহ করে আগে নিবন্ধন করুন।' },
  DAILY_ERROR_BP_REQUIRED:        { en: 'Blood pressure is required (e.g. 120/80).', bn: 'রক্তচাপ প্রয়োজন (যেমন ১২০/৮০)।' },
  DAILY_ERROR_BP_FORMAT:          { en: 'Please enter blood pressure in the format "systolic/diastolic" (e.g. 120/80)', bn: 'অনুগ্রহ করে "সিস্টোলিক/ডায়াস্টোলিক" ফর্ম্যাটে রক্তচাপ লিখুন (যেমন ১২০/৮০)' },
  DAILY_ERROR_BP_RANGE:           { en: 'Invalid BP. Out of range',                bn: 'অবৈধ রক্তচাপ। সীমার বাইরে' },
  DAILY_ERROR_PULSE_RANGE:        { en: 'Invalid pulse. Out of range',             bn: 'অবৈধ পালস। সীমার বাইরে' },
  DAILY_SUCCESS_OFFLINE:          { en: 'Saved to offline queue successfully! It will sync when connection is restored.', bn: 'অফলাইন কিউতে সফলভাবে সেভ করা হয়েছে! সংযোগ পুনরুদ্ধার হলে সিঙ্ক হবে।' },
  DAILY_ERROR_LOCAL_SAVE:         { en: 'Failed to save data locally.',            bn: 'স্থানীয়ভাবে ডেটা সেভ করতে ব্যর্থ।' },
  DAILY_SUCCESS_RECORDED:         { en: 'Daily check recorded! Risk status: {riskLevel}', bn: 'দৈনিক চেক রেকর্ড হয়েছে! ঝুঁকির অবস্থা: {riskLevel}' },
  DAILY_ERROR_SAVE_FAILED:        { en: 'Failed to save daily check details.',     bn: 'দৈনিক চেকের বিবরণ সেভ করতে ব্যর্থ।' },
  DAILY_ERROR_NETWORK:            { en: 'Network request failed. Please try saving offline instead.', bn: 'নেটওয়ার্ক অনুরোধ ব্যর্থ। অনুগ্রহ করে অফলাইনে সেভ করুন।' },
  DAILY_PROFILE_REQUIRED:         { en: 'Profile Setup Required',                  bn: 'প্রোফাইল সেটআপ প্রয়োজন' },
  DAILY_PROFILE_REQUIRED_DESC:    { en: 'You need to complete your pregnancy profile before recording vitals.', bn: 'ভাইটাল রেকর্ড করার আগে আপনার গর্ভাবস্থার প্রোফাইল সম্পূর্ণ করতে হবে।' },
  DAILY_COMPLETE_PROFILE:         { en: 'Complete My Profile',                     bn: 'আমার প্রোফাইল সম্পূর্ণ করুন' },
  DAILY_RECORD_HEADING:           { en: "Record Today's Vitals",                   bn: 'আজকের ভাইটাল রেকর্ড করুন' },
  DAILY_BP_LABEL:                 { en: 'Blood Pressure (mmHg) *',                 bn: 'রক্তচাপ (mmHg) *' },
  DAILY_BP_PLACEHOLDER:           { en: 'e.g. 120/80',                             bn: 'যেমন ১২০/৮০' },
  DAILY_WEIGHT_LABEL:             { en: 'Weight (kg)',                              bn: 'ওজন (কেজি)' },
  DAILY_WEIGHT_PLACEHOLDER:       { en: 'e.g. 62',                                 bn: 'যেমন ৬২' },
  DAILY_TEMP_LABEL:               { en: 'Temperature (°C)',                         bn: 'তাপমাত্রা (°C)' },
  DAILY_TEMP_PLACEHOLDER:         { en: 'e.g. 36.8',                               bn: 'যেমন ৩৬.৮' },
  DAILY_PULSE_LABEL:              { en: 'Pulse (bpm)',                              bn: 'পালস (bpm)' },
  DAILY_PULSE_PLACEHOLDER:        { en: 'e.g. 75',                                 bn: 'যেমন ৭৫' },
  DAILY_SYMPTOMS_LABEL:           { en: 'Symptoms (comma-separated)',               bn: 'উপসর্গ (কমা দিয়ে আলাদা)' },
  DAILY_SYMPTOMS_PLACEHOLDER:     { en: 'e.g. Headache, Nausea',                   bn: 'যেমন মাথাব্যথা, বমি ভাব' },
  DAILY_SAVING:                   { en: 'Saving...',                                bn: 'সেভ হচ্ছে...' },
  DAILY_SAVE_OFFLINE:             { en: 'Save Offline',                             bn: 'অফলাইনে সেভ' },

  // ── Emergency SOS ────────────────────────────────────────
  EMERGENCY_PAGE_TITLE:           { en: 'Emergency SOS',                           bn: 'জরুরি এসওএস' },
  EMERGENCY_ALERT_HEADING:        { en: 'Emergency Alert',                         bn: 'জরুরি সতর্কতা' },
  EMERGENCY_INSTRUCTIONS:         { en: 'Press the SOS button to alert nearby health workers and emergency services. Your GPS location will be shared automatically.', bn: 'কাছের স্বাস্থ্যকর্মী এবং জরুরি সেবায় সতর্ক করতে এসওএস বোতাম টিপুন। আপনার জিপিএস অবস্থান স্বয়ংক্রিয়ভাবে শেয়ার করা হবে।' },
  EMERGENCY_DISPATCHED:           { en: 'SOS Dispatched: Help is on the way!',     bn: 'এসওএস প্রেরিত: সাহায্য আসছে!' },
  EMERGENCY_GPS_COORDS:           { en: 'GPS Coordinates: {lat}, {lng}',           bn: 'জিপিএস স্থানাঙ্ক: {lat}, {lng}' },
  EMERGENCY_SYSTEM_READY:         { en: 'PulseGuard Security System: Ready',       bn: 'পালসগার্ড সিকিউরিটি সিস্টেম: প্রস্তুত' },
  EMERGENCY_OFFLINE_ACTIVE:       { en: 'Offline Mode Active',                     bn: 'অফলাইন মোড সক্রিয়' },
  EMERGENCY_GEO_NOT_SUPPORTED:    { en: 'Geolocation is not supported by your browser', bn: 'আপনার ব্রাউজার জিওলোকেশন সমর্থন করে না' },
  EMERGENCY_GEO_FAILED:           { en: 'Unable to retrieve location. Please make sure location access is enabled.', bn: 'অবস্থান পুনরুদ্ধার করতে অক্ষম। অনুগ্রহ করে নিশ্চিত করুন যে লোকেশন অ্যাক্সেস সক্ষম আছে।' },
  EMERGENCY_SOS_MESSAGE:          { en: 'SOS Emergency Alert triggered from Patient Portal.', bn: 'রোগী পোর্টাল থেকে এসওএস জরুরি সতর্কতা ট্রিগার করা হয়েছে।' },
  EMERGENCY_SEND_FAILED:          { en: 'Failed to send SOS: {error}',             bn: 'এসওএস পাঠাতে ব্যর্থ: {error}' },
  EMERGENCY_SEND_FAILED_GENERIC:  { en: 'Failed to send SOS alert. Please try again.', bn: 'এসওএস সতর্কতা পাঠাতে ব্যর্থ। আবার চেষ্টা করুন।' },
  EMERGENCY_UNKNOWN_ERROR:        { en: 'Unknown error',                           bn: 'অজানা ত্রুটি' },
  EMERGENCY_SOS_BTN_SENT:         { en: 'SENT',                                    bn: 'প্রেরিত' },
  EMERGENCY_SOS_BTN:              { en: 'SOS',                                     bn: 'এসওএস' },
  EMERGENCY_FETCHING_LOCATION:    { en: 'Fetching Location…',                      bn: 'অবস্থান নির্ণয় হচ্ছে…' },
  EMERGENCY_SHARE_GPS:            { en: 'Share GPS Location',                      bn: 'জিপিএস অবস্থান শেয়ার করুন' },
  EMERGENCY_NOTIFY_WORKER:        { en: 'Notify Health Worker',                    bn: 'স্বাস্থ্যকর্মীকে জানান' },
  EMERGENCY_CALL_SERVICES:        { en: 'Call Emergency Services',                 bn: 'জরুরি সেবায় কল করুন' },

  // ── Nutrition ────────────────────────────────────────────
  NUTRITION_PAGE_TITLE:           { en: 'Nutrition Guide',                         bn: 'পুষ্টি নির্দেশিকা' },
  NUTRITION_TAG_ALL:              { en: 'All',                                     bn: 'সব' },
  NUTRITION_TAG_IRON_RICH:        { en: 'Iron Rich',                               bn: 'আয়রন সমৃদ্ধ' },
  NUTRITION_TAG_PROTEIN:          { en: 'Protein',                                 bn: 'প্রোটিন' },
  NUTRITION_TAG_CALCIUM:          { en: 'Calcium',                                 bn: 'ক্যালসিয়াম' },
  NUTRITION_TAG_VITAMINS:         { en: 'Vitamins',                                bn: 'ভিটামিন' },
  NUTRITION_RECOMMENDED_HEADING:  { en: 'Recommended Foods',                       bn: 'প্রস্তাবিত খাবার' },
  NUTRITION_RECOMMENDED_DESC:     { en: 'Essential nutrients for your pregnancy',   bn: 'আপনার গর্ভাবস্থার জন্য প্রয়োজনীয় পুষ্টি' },
  NUTRITION_NO_RECOMMENDED:       { en: 'No recommended foods match the selected filter.', bn: 'নির্বাচিত ফিল্টারের সাথে কোনো প্রস্তাবিত খাবার মেলেনি।' },
  NUTRITION_AVOID_HEADING:        { en: 'Foods to Avoid',                           bn: 'যেসব খাবার এড়িয়ে চলুন' },
  NUTRITION_AVOID_DESC:           { en: 'Minimize risk during pregnancy',           bn: 'গর্ভাবস্থায় ঝুঁকি কমান' },
  NUTRITION_LOCAL_HEADING:        { en: 'Local Affordable Foods',                   bn: 'স্থানীয় সাশ্রয়ী খাবার' },
  NUTRITION_LOCAL_DESC:           { en: 'Nutritious options available in your region', bn: 'আপনার এলাকায় পাওয়া যায় এমন পুষ্টিকর বিকল্প' },
  NUTRITION_NO_LOCAL:             { en: 'No local foods match the selected filter.', bn: 'নির্বাচিত ফিল্টারের সাথে কোনো স্থানীয় খাবার মেলেনি।' },

  // ── Onboarding ───────────────────────────────────────────
  ONBOARDING_PAGE_TITLE:          { en: 'Set Up Profile',                          bn: 'প্রোফাইল সেটআপ করুন' },
  ONBOARDING_WELCOME:             { en: 'Welcome, {name}!',                        bn: 'স্বাগতম, {name}!' },
  ONBOARDING_WELCOME_DESC:        { en: 'To get started with PulseGuard, we need a few details to set up your maternal health profile. This will unlock vitals tracking, AI health checks, and personalised guidance.', bn: 'পালসগার্ড শুরু করতে আপনার মাতৃস্বাস্থ্য প্রোফাইল সেটআপ করতে কিছু তথ্য প্রয়োজন। এটি ভাইটাল ট্র্যাকিং, এআই স্বাস্থ্য পরীক্ষা এবং ব্যক্তিগত নির্দেশনা আনলক করবে।' },
  ONBOARDING_FORM_HEADING:        { en: 'Medical Profile Setup',                   bn: 'মেডিকেল প্রোফাইল সেটআপ' },
  ONBOARDING_REQUIRED_NOTE:       { en: 'All fields marked * are required.',        bn: '* চিহ্নিত সকল ক্ষেত্র আবশ্যক।' },
  ONBOARDING_WEEK_LABEL:          { en: 'Current Pregnancy Week *',                 bn: 'বর্তমান গর্ভাবস্থার সপ্তাহ *' },
  ONBOARDING_WEEK_PLACEHOLDER:    { en: 'e.g. 24',                                 bn: 'যেমন ২৪' },
  ONBOARDING_WEEK_HINT:           { en: 'Enter a value between 1 and 45.',         bn: '১ থেকে ৪৫ এর মধ্যে একটি মান দিন।' },
  ONBOARDING_AGE_LABEL:           { en: 'Your Age',                                bn: 'আপনার বয়স' },
  ONBOARDING_AGE_PLACEHOLDER:     { en: 'e.g. 26',                                 bn: 'যেমন ২৬' },
  ONBOARDING_VILLAGE_LABEL:       { en: 'Village / Clinic Area',                    bn: 'গ্রাম / ক্লিনিক এলাকা' },
  ONBOARDING_VILLAGE_PLACEHOLDER: { en: 'e.g. Kurigram Village A',                 bn: 'যেমন কুড়িগ্রাম গ্রাম ক' },
  ONBOARDING_SAVING:              { en: 'Setting up profile…',                     bn: 'প্রোফাইল সেটআপ হচ্ছে…' },
  ONBOARDING_SUBMIT:              { en: '✓ Complete Registration',                 bn: '✓ নিবন্ধন সম্পূর্ণ করুন' },
  ONBOARDING_ERROR_WEEK_REQUIRED: { en: 'Please enter your current gestational week.', bn: 'অনুগ্রহ করে আপনার বর্তমান গর্ভাবস্থার সপ্তাহ লিখুন।' },
  ONBOARDING_ERROR_WEEK_RANGE:    { en: 'Gestational week must be between 1 and 45.', bn: 'গর্ভাবস্থার সপ্তাহ ১ থেকে ৪৫ এর মধ্যে হতে হবে।' },
  ONBOARDING_ERROR_CREATE_FAILED: { en: 'Failed to create patient profile.',        bn: 'রোগীর প্রোফাইল তৈরি করতে ব্যর্থ।' },
  ONBOARDING_ERROR_GENERIC:       { en: 'Something went wrong. Please try again.', bn: 'কিছু ভুল হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।' },

  // ── Profile ──────────────────────────────────────────────
  PROFILE_PAGE_TITLE:             { en: 'Profile',                                 bn: 'প্রোফাইল' },
  PROFILE_LOADING:                { en: 'Loading profile details…',                bn: 'প্রোফাইলের বিবরণ লোড হচ্ছে…' },
  PROFILE_FALLBACK_NAME:          { en: 'User Profile',                            bn: 'ব্যবহারকারী প্রোফাইল' },
  PROFILE_EDIT_HEADING:           { en: 'Edit Profile',                            bn: 'প্রোফাইল সম্পাদনা' },
  PROFILE_DETAILS_HEADING:        { en: 'Profile Details',                         bn: 'প্রোফাইলের বিবরণ' },
  PROFILE_FULL_NAME_LABEL:        { en: 'Full Name *',                             bn: 'পূর্ণ নাম *' },
  PROFILE_NAME_PLACEHOLDER:       { en: 'Enter your name',                         bn: 'আপনার নাম লিখুন' },
  PROFILE_EMAIL_LABEL:            { en: 'Email Address',                           bn: 'ইমেইল ঠিকানা' },
  PROFILE_EMAIL_PLACEHOLDER:      { en: 'e.g. name@domain.com',                   bn: 'যেমন name@domain.com' },
  PROFILE_PHONE_LABEL:            { en: 'Phone Number',                            bn: 'ফোন নম্বর' },
  PROFILE_PHONE_PLACEHOLDER:      { en: 'e.g. +880123456789',                     bn: 'যেমন +880123456789' },
  PROFILE_VILLAGE_LABEL:          { en: 'Village Clinic Area',                     bn: 'গ্রাম ক্লিনিক এলাকা' },
  PROFILE_VILLAGE_PLACEHOLDER:    { en: 'e.g. Village A',                          bn: 'যেমন গ্রাম ক' },
  PROFILE_GESTATIONAL_WEEK_LABEL: { en: 'Gestational Pregnancy Week',              bn: 'গর্ভাবস্থার সপ্তাহ' },
  PROFILE_GESTATIONAL_WEEK_PLACEHOLDER: { en: 'e.g. 24',                           bn: 'যেমন ২৪' },
  PROFILE_DETAIL_PREGNANCY_WEEK:  { en: 'Pregnancy Week',                          bn: 'গর্ভাবস্থার সপ্তাহ' },
  PROFILE_DETAIL_RISK_LEVEL:      { en: 'Risk Level',                              bn: 'ঝুঁকির মাত্রা' },
  PROFILE_DETAIL_VILLAGE:         { en: 'Village',                                 bn: 'গ্রাম' },
  PROFILE_DETAIL_PHONE:           { en: 'Phone',                                   bn: 'ফোন' },
  PROFILE_DETAIL_EMAIL:           { en: 'Email',                                   bn: 'ইমেইল' },
  PROFILE_DETAIL_ASSIGNED_PATIENTS: { en: 'Assigned Patients',                     bn: 'নির্ধারিত রোগী' },
  PROFILE_ADMIN_SYSTEM_ROLE:      { en: 'System Role',                             bn: 'সিস্টেম ভূমিকা' },
  PROFILE_STATUS_LABEL:           { en: 'Profile Status',                          bn: 'প্রোফাইলের অবস্থা' },
  PROFILE_STATUS_PENDING:         { en: 'Pending Registration Completion',         bn: 'নিবন্ধন সম্পূর্ণ করার অপেক্ষায়' },
  PROFILE_COMPLETE_REGISTRATION:  { en: 'Complete Registration',                   bn: 'নিবন্ধন সম্পূর্ণ করুন' },
  PROFILE_SAVING:                 { en: 'Saving...',                                bn: 'সেভ হচ্ছে...' },
  PROFILE_SAVE_CHANGES:           { en: 'Save Changes',                            bn: 'পরিবর্তন সেভ করুন' },
  PROFILE_EDIT_BTN:               { en: 'Edit Profile',                            bn: 'প্রোফাইল সম্পাদনা' },
  PROFILE_ERROR_NAME_REQUIRED:    { en: 'Name is required',                        bn: 'নাম আবশ্যক' },
  PROFILE_ERROR_UPDATE_USER:      { en: 'Failed to update user profile details',   bn: 'ব্যবহারকারীর প্রোফাইল বিবরণ আপডেট করতে ব্যর্থ' },
  PROFILE_ERROR_UPDATE_PATIENT:   { en: 'Failed to update patient details',        bn: 'রোগীর বিবরণ আপডেট করতে ব্যর্থ' },
  PROFILE_SUCCESS_UPDATED:        { en: 'Profile updated successfully!',           bn: 'প্রোফাইল সফলভাবে আপডেট হয়েছে!' },
  PROFILE_ERROR_GENERIC:          { en: 'An error occurred while saving profile.', bn: 'প্রোফাইল সেভ করতে একটি ত্রুটি ঘটেছে।' },
  PROFILE_PATIENT_ID:             { en: 'Patient ID: PG-{id}',                     bn: 'রোগী আইডি: PG-{id}' },
  PROFILE_WORKER_ID:              { en: 'Health Worker ID: HW-{id}',               bn: 'স্বাস্থ্যকর্মী আইডি: HW-{id}' },

  // ── Records ──────────────────────────────────────────────
  RECORDS_PAGE_TITLE:             { en: 'Medical Records',                         bn: 'মেডিকেল রেকর্ড' },
  RECORDS_HEADING:                { en: 'Your Records',                            bn: 'আপনার রেকর্ড' },
  RECORDS_EXPORT:                 { en: '⬇️ Export CSV',                           bn: '⬇️ CSV রপ্তানি' },
  RECORDS_LOADING:                { en: 'Loading records…',                        bn: 'রেকর্ড লোড হচ্ছে…' },
  RECORDS_NO_RECORDS:             { en: 'No records recorded yet.',                bn: 'এখনো কোনো রেকর্ড নেই।' },
  RECORDS_BP_LABEL:               { en: 'BP:',                                     bn: 'রক্তচাপ:' },
  RECORDS_WEIGHT_LABEL:           { en: 'Weight:',                                 bn: 'ওজন:' },
  RECORDS_TEMP_LABEL:             { en: 'Temp:',                                   bn: 'তাপমাত্রা:' },
  RECORDS_PULSE_LABEL:            { en: 'Pulse:',                                  bn: 'পালস:' },

  // ── Patient Alerts ───────────────────────────────────────
  PATIENT_ALERTS_TITLE:           { en: 'Alerts',                                  bn: 'সতর্কতা' },
  PATIENT_ALERTS_WELCOME_TITLE:   { en: 'Welcome to PulseGuard',                   bn: 'পালসগার্ড-এ স্বাগতম' },
  PATIENT_ALERTS_WELCOME_MSG:     { en: 'Monitor your blood pressure daily and stay connected with your healthcare worker.', bn: 'প্রতিদিন আপনার রক্তচাপ পর্যবেক্ষণ করুন এবং আপনার স্বাস্থ্যকর্মীর সাথে সংযুক্ত থাকুন।' },
  PATIENT_ALERTS_SYNC_TITLE:      { en: 'Sync Complete',                           bn: 'সিঙ্ক সম্পূর্ণ' },
  PATIENT_ALERTS_SYNC_MSG:        { en: 'All your offline health logs have been safely backed up to the server.', bn: 'আপনার সকল অফলাইন স্বাস্থ্য লগ নিরাপদে সার্ভারে ব্যাকআপ হয়েছে।' },
  PATIENT_ALERTS_NOTIFICATIONS:   { en: 'Notifications',                           bn: 'বিজ্ঞপ্তি' },

  // ── Worker Dashboard ─────────────────────────────────────
  WORKER_DASHBOARD_TITLE:         { en: 'Health Worker',                           bn: 'স্বাস্থ্যকর্মী' },
  WORKER_BANNER_TITLE:            { en: 'Sync Center',                             bn: 'সিঙ্ক সেন্টার' },
  WORKER_BANNER_PATIENTS_ASSIGNED: { en: 'patients assigned',                      bn: 'জন রোগী নির্ধারিত' },
  WORKER_BANNER_OPEN_SYNC:        { en: 'Open Sync',                               bn: 'সিঙ্ক খুলুন' },
  WORKER_TODAYS_KPIS:             { en: "Today's KPIs",                            bn: 'আজকের কেপিআই' },
  WORKER_TOTAL_PATIENTS:          { en: 'Total Patients',                          bn: 'মোট রোগী' },
  WORKER_HIGH_RISK_CASES:         { en: 'High Risk Cases',                         bn: 'উচ্চ ঝুঁকির কেস' },
  WORKER_MODERATE_RISK_CASES:     { en: 'Moderate Risk Cases',                     bn: 'মাঝারি ঝুঁকির কেস' },
  WORKER_LOW_RISK_CASES:          { en: 'Low Risk Cases',                          bn: 'নিম্ন ঝুঁকির কেস' },
  WORKER_QUICK_ACTIONS:           { en: 'Quick Actions',                           bn: 'দ্রুত কার্যক্রম' },
  WORKER_PATIENT_LIST_LINK:       { en: 'Patient List',                            bn: 'রোগীর তালিকা' },
  WORKER_AI_ASSISTANT_LINK:       { en: 'AI Assistant',                            bn: 'এআই সহকারী' },
  WORKER_SYNC_CENTER_LINK:        { en: 'Sync Center',                             bn: 'সিঙ্ক সেন্টার' },
  WORKER_HIGH_RISK_HEADING:       { en: 'High Risk Patients',                      bn: 'উচ্চ ঝুঁকির রোগী' },
  WORKER_PATIENTS_COUNT:          { en: 'patients',                                bn: 'জন রোগী' },
  WORKER_NO_HIGH_RISK:            { en: 'No high risk patients',                   bn: 'কোনো উচ্চ ঝুঁকির রোগী নেই' },

  // ── Worker AI Analysis ───────────────────────────────────
  AI_PAGE_TITLE:                  { en: 'AI Analysis',                             bn: 'এআই বিশ্লেষণ' },
  AI_RISK_ASSESSMENT_HEADING:     { en: 'AI Risk Assessment',                      bn: 'এআই ঝুঁকি মূল্যায়ন' },
  AI_SELECT_PATIENT_LABEL:        { en: 'Select Patient',                          bn: 'রোগী নির্বাচন করুন' },
  AI_CHOOSE_PATIENT:              { en: 'Choose patient…',                         bn: 'রোগী বাছাই করুন…' },
  AI_ANALYZING:                   { en: 'Analyzing…',                              bn: 'বিশ্লেষণ হচ্ছে…' },
  AI_RUN_ANALYSIS:                { en: 'Run AI Analysis',                         bn: 'এআই বিশ্লেষণ চালান' },
  AI_RISK_PREDICTION:             { en: 'Risk Prediction:',                        bn: 'ঝুঁকি পূর্বাভাস:' },
  AI_RISK_SCORE:                  { en: 'Risk Score',                              bn: 'ঝুঁকি স্কোর' },
  AI_PREECLAMPSIA_FLAG:           { en: 'Preeclampsia Flag',                       bn: 'প্রি-একলাম্পসিয়া সতর্কতা' },
  AI_PREECLAMPSIA_FLAG_DESC:      { en: 'AI model has flagged potential preeclampsia risk.', bn: 'এআই মডেল সম্ভাব্য প্রি-একলাম্পসিয়া ঝুঁকি চিহ্নিত করেছে।' },
  AI_CONTRIBUTING_FACTORS:        { en: 'Contributing Factors:',                   bn: 'অবদানকারী কারণসমূহ:' },
  AI_MODEL_LABEL:                 { en: 'Model:',                                  bn: 'মডেল:' },
  AI_LONGITUDINAL_SUMMARY:        { en: 'Longitudinal Summary',                    bn: 'দীর্ঘকালীন সারসংক্ষেপ' },
  AI_ASSESSMENT:                  { en: 'AI Assessment',                           bn: 'এআই মূল্যায়ন' },
  AI_RECOMMENDATIONS:             { en: 'Recommendations',                         bn: 'সুপারিশ' },
  AI_SOURCES:                     { en: 'Sources:',                                bn: 'সূত্র:' },
  AI_SELECT_PATIENT_FALLBACK:     { en: 'Select a patient',                        bn: 'একজন রোগী নির্বাচন করুন' },

  // ── Worker Alerts ────────────────────────────────────────
  WORKER_ALERTS_TITLE:            { en: 'Alerts Center',                           bn: 'সতর্কতা কেন্দ্র' },
  WORKER_ALERTS_ACTIVE_SOS:       { en: 'Active Emergency SOS',                    bn: 'সক্রিয় জরুরি এসওএস' },
  WORKER_ALERTS_ACTIVE_BADGE:     { en: 'Active',                                  bn: 'সক্রিয়' },
  WORKER_ALERTS_LOADING:          { en: 'Loading alerts…',                         bn: 'সতর্কতা লোড হচ্ছে…' },
  WORKER_ALERTS_ALL_QUIET:        { en: '🎉 All quiet. No pending emergency alerts.', bn: '🎉 সব ঠিক আছে। কোনো মুলতুবি জরুরি সতর্কতা নেই।' },
  WORKER_ALERTS_NO_VILLAGE:       { en: 'No village recorded',                     bn: 'কোনো গ্রাম রেকর্ড করা হয়নি' },
  WORKER_ALERTS_TRIGGERED:        { en: 'Triggered:',                              bn: 'ট্রিগার হয়েছে:' },
  WORKER_ALERTS_LOCATION_SHARED:  { en: '📍 Location Shared:',                    bn: '📍 অবস্থান শেয়ার করা হয়েছে:' },
  WORKER_ALERTS_OPEN_MAPS:        { en: 'Open in Google Maps',                     bn: 'গুগল ম্যাপে খুলুন' },
  WORKER_ALERTS_MARK_RESOLVED:    { en: 'Mark Resolved',                           bn: 'সমাধান হিসেবে চিহ্নিত করুন' },
  WORKER_ALERTS_DISMISS:          { en: 'Dismiss',                                 bn: 'বাতিল করুন' },
  WORKER_ALERTS_RESOLVED_HEADING: { en: 'Resolved Alerts History',                 bn: 'সমাধিত সতর্কতার ইতিহাস' },
  WORKER_ALERTS_TOTAL:            { en: 'total',                                   bn: 'মোট' },
  WORKER_ALERTS_NO_RESOLVED:      { en: 'No history of resolved alerts.',          bn: 'সমাধিত সতর্কতার কোনো ইতিহাস নেই।' },
  WORKER_ALERTS_RESOLVED_LABEL:   { en: 'Resolved:',                               bn: 'সমাধান:' },
  WORKER_ALERTS_FAILED_UPDATE:    { en: 'Failed to update alert:',                 bn: 'সতর্কতা আপডেট করতে ব্যর্থ:' },

  // ── Worker Patient Details ───────────────────────────────
  PATIENT_TAB_OVERVIEW:           { en: 'Overview',                                bn: 'সারসংক্ষেপ' },
  PATIENT_TAB_VITALS:             { en: 'Vitals',                                  bn: 'ভাইটাল' },
  PATIENT_TAB_AI_INSIGHTS:        { en: 'AI Insights',                             bn: 'এআই ইনসাইটস' },
  PATIENT_TAB_HISTORY:            { en: 'History',                                 bn: 'ইতিহাস' },
  PATIENT_DETAILS_TITLE:          { en: 'Patient Details',                         bn: 'রোগীর বিবরণ' },
  PATIENT_LOADING:                { en: 'Loading patient…',                        bn: 'রোগীর তথ্য লোড হচ্ছে…' },
  PATIENT_NOT_FOUND:              { en: 'Patient not found',                       bn: 'রোগী পাওয়া যায়নি' },
  PATIENT_AGE_LABEL:              { en: 'Age:',                                    bn: 'বয়স:' },
  PATIENT_PREGNANCY_WEEK:         { en: 'Pregnancy Week',                          bn: 'গর্ভাবস্থার সপ্তাহ' },
  PATIENT_BLOOD_PRESSURE:         { en: 'Blood Pressure',                          bn: 'রক্তচাপ' },
  PATIENT_WEIGHT:                 { en: 'Weight',                                  bn: 'ওজন' },
  PATIENT_PULSE:                  { en: 'Pulse',                                   bn: 'পালস' },
  PATIENT_TEMPERATURE:            { en: 'Temperature',                             bn: 'তাপমাত্রা' },
  PATIENT_WEIGHT_UNIT:            { en: 'kg',                                      bn: 'কেজি' },
  PATIENT_PULSE_UNIT:             { en: 'bpm',                                     bn: 'বিপিএম' },
  PATIENT_TEMPERATURE_UNIT:       { en: '°C',                                      bn: '°C' },
  PATIENT_HIGH_RISK_ALERT_TITLE:  { en: 'High Risk Alert',                         bn: 'উচ্চ ঝুঁকি সতর্কতা' },
  PATIENT_HIGH_RISK_ALERT_DESC:   { en: 'Patient shows elevated BP ({bp}). Risk score: {score}%; recommend immediate clinical referral.', bn: 'রোগীর রক্তচাপ উচ্চ ({bp})। ঝুঁকি স্কোর: {score}%; তাৎক্ষণিক ক্লিনিক্যাল রেফারেল সুপারিশ করা হচ্ছে।' },
  PATIENT_VITALS_HISTORY:         { en: 'Vitals History',                          bn: 'ভাইটাল ইতিহাস' },
  PATIENT_VITALS_BP:              { en: 'BP:',                                     bn: 'রক্তচাপ:' },
  PATIENT_VITALS_WEIGHT:          { en: 'Weight:',                                 bn: 'ওজন:' },
  PATIENT_VITALS_PULSE:           { en: 'Pulse:',                                  bn: 'পালস:' },
  PATIENT_VITALS_RISK:            { en: 'Risk:',                                   bn: 'ঝুঁকি:' },
  PATIENT_NO_VITALS:              { en: 'No vitals recorded yet',                  bn: 'এখনো কোনো ভাইটাল রেকর্ড হয়নি' },
  PATIENT_AI_RISK_ASSESSMENT:     { en: 'Risk Assessment',                         bn: 'ঝুঁকি মূল্যায়ন' },
  PATIENT_AI_RISK_SCORE:          { en: 'AI Risk Score',                           bn: 'এআই ঝুঁকি স্কোর' },
  PATIENT_RISK_FACTORS:           { en: 'Risk Factors',                            bn: 'ঝুঁকির কারণসমূহ' },
  PATIENT_AI_PREECLAMPSIA_DESC:   { en: 'AI model has flagged potential preeclampsia risk. Immediate clinical referral recommended.', bn: 'এআই মডেল সম্ভাব্য প্রি-একলাম্পসিয়া ঝুঁকি চিহ্নিত করেছে। তাৎক্ষণিক ক্লিনিক্যাল রেফারেল সুপারিশ করা হচ্ছে।' },
  PATIENT_NOT_ANALYZED:           { en: 'Not yet analyzed',                        bn: 'এখনো বিশ্লেষণ হয়নি' },
  PATIENT_RUN_HINT:               { en: 'Click "Run AI Analysis" below to get fresh prediction', bn: 'নতুন পূর্বাভাস পেতে নিচে "এআই বিশ্লেষণ চালান" ক্লিক করুন' },
  PATIENT_VISIT_HISTORY:          { en: 'Visit History',                           bn: 'ভিজিট ইতিহাস' },
  PATIENT_VILLAGE_FALLBACK:       { en: 'Village',                                 bn: 'গ্রাম' },
  PATIENT_RECORDED_BY:            { en: 'Recorded by',                             bn: 'রেকর্ডকারী' },
  PATIENT_WORKER_FALLBACK:        { en: 'Worker',                                  bn: 'কর্মী' },
  PATIENT_COMPLETE_BADGE:         { en: 'Complete',                                bn: 'সম্পূর্ণ' },
  PATIENT_NO_VISIT_HISTORY:       { en: 'No visit history',                        bn: 'কোনো ভিজিট ইতিহাস নেই' },
  PATIENT_ASSIGNED_WORKER:        { en: 'Assigned Worker:',                        bn: 'নির্ধারিত কর্মী:' },
  PATIENT_RECORD_VITALS:          { en: 'Record Vitals',                           bn: 'ভাইটাল রেকর্ড' },
  PATIENT_RUN_AI_ANALYSIS:        { en: 'Run AI Analysis',                         bn: 'এআই বিশ্লেষণ চালান' },

  // ── Worker Patient List ──────────────────────────────────
  PATIENT_LIST_TITLE:             { en: 'Patient List',                            bn: 'রোগীর তালিকা' },
  PATIENT_LIST_SEARCH_PLACEHOLDER: { en: 'Search patient by name or village…',     bn: 'নাম বা গ্রাম দিয়ে রোগী খুঁজুন…' },
  PATIENT_LIST_HEADING:           { en: 'Patients',                                bn: 'রোগীরা' },
  PATIENT_LIST_RESULTS:           { en: 'results',                                 bn: 'ফলাফল' },
  PATIENT_LIST_LOADING:           { en: 'Loading patients…',                       bn: 'রোগীদের তথ্য লোড হচ্ছে…' },
  PATIENT_LIST_NO_MATCH:          { en: 'No patients match your search.',          bn: 'আপনার অনুসন্ধানের সাথে কোনো রোগী মেলেনি।' },
  FILTER_ALL:                     { en: 'All',                                     bn: 'সব' },

  // ── Worker Sync Center ───────────────────────────────────
  SYNC_PAGE_TITLE:                { en: 'Sync Center',                             bn: 'সিঙ্ক সেন্টার' },
  SYNC_BANNER_TITLE:              { en: 'Sync Status',                             bn: 'সিঙ্ক অবস্থা' },
  SYNC_CONNECTED:                 { en: 'Connected to server',                     bn: 'সার্ভারের সাথে সংযুক্ত' },
  SYNC_OFFLINE_MSG:               { en: 'Offline; data will sync when connected',  bn: 'অফলাইন; সংযোগ হলে ডেটা সিঙ্ক হবে' },
  SYNC_REFRESH:                   { en: 'Refresh',                                 bn: 'রিফ্রেশ' },
  SYNC_CONFLICTS_LABEL:           { en: 'Conflicts',                               bn: 'দ্বন্দ্ব' },
  SYNC_CONNECTION_STATUS:         { en: 'Connection Status',                       bn: 'সংযোগের অবস্থা' },
  SYNC_ALL_SYNCED:                { en: 'All data synced',                         bn: 'সকল ডেটা সিঙ্ক হয়েছে' },
  SYNC_WAITING_CONNECTION:        { en: 'Waiting for connection...',               bn: 'সংযোগের অপেক্ষায়...' },
  SYNC_LOADING_CONFLICTS:         { en: 'Loading conflicts…',                      bn: 'দ্বন্দ্ব লোড হচ্ছে…' },
  SYNC_NO_CONFLICTS:              { en: 'No conflicts; all data is in sync',       bn: 'কোনো দ্বন্দ্ব নেই; সকল ডেটা সিঙ্কে আছে' },
  SYNC_PATIENT_FALLBACK:          { en: 'Patient',                                 bn: 'রোগী' },
  SYNC_CONFLICT_BADGE:            { en: 'Conflict',                                bn: 'দ্বন্দ্ব' },
  SYNC_LOCAL:                     { en: 'Local',                                   bn: 'স্থানীয়' },
  SYNC_SERVER:                    { en: 'Server',                                  bn: 'সার্ভার' },
  SYNC_KEEP_LOCAL:                { en: 'Keep Local',                              bn: 'স্থানীয় রাখুন' },
  SYNC_KEEP_SERVER:               { en: 'Keep Server',                             bn: 'সার্ভারেরটি রাখুন' },

  // ── Worker Vitals Entry ──────────────────────────────────
  VITALS_PAGE_TITLE:              { en: 'Record Vitals',                           bn: 'ভাইটাল রেকর্ড' },
  VITALS_INPUT_HEADING:           { en: 'Vitals Input',                            bn: 'ভাইটাল ইনপুট' },
  VITALS_PATIENT_LABEL:           { en: 'Patient',                                 bn: 'রোগী' },
  VITALS_SELECT_PATIENT:          { en: 'Select patient…',                         bn: 'রোগী নির্বাচন করুন…' },
  VITALS_BP_SYSTOLIC_LABEL:       { en: 'BP Systolic (mmHg) *',                    bn: 'সিস্টোলিক রক্তচাপ (mmHg) *' },
  VITALS_BP_SYSTOLIC_PLACEHOLDER: { en: '120',                                     bn: '১২০' },
  VITALS_BP_DIASTOLIC_LABEL:      { en: 'BP Diastolic (mmHg) *',                   bn: 'ডায়াস্টোলিক রক্তচাপ (mmHg) *' },
  VITALS_BP_DIASTOLIC_PLACEHOLDER: { en: '80',                                     bn: '৮০' },
  VITALS_WEIGHT_LABEL:            { en: 'Weight (kg)',                              bn: 'ওজন (কেজি)' },
  VITALS_WEIGHT_PLACEHOLDER:      { en: '62.0',                                    bn: '৬২.০' },
  VITALS_PULSE_LABEL:             { en: 'Pulse (bpm)',                              bn: 'পালস (bpm)' },
  VITALS_PULSE_PLACEHOLDER:       { en: '78',                                      bn: '৭৮' },
  VITALS_TEMP_LABEL:              { en: 'Temperature (°C)',                         bn: 'তাপমাত্রা (°C)' },
  VITALS_TEMP_PLACEHOLDER:        { en: '36.8',                                    bn: '৩৬.৮' },
  VITALS_SYMPTOMS_LABEL:          { en: 'Symptoms (comma-separated)',               bn: 'উপসর্গ (কমা দিয়ে আলাদা)' },
  VITALS_SYMPTOMS_PLACEHOLDER:    { en: 'Headache, fatigue, swelling...',           bn: 'মাথাব্যথা, ক্লান্তি, ফোলাভাব...' },
  VITALS_VALIDATION_ERROR:        { en: 'Please select a patient and enter BP readings', bn: 'অনুগ্রহ করে একজন রোগী নির্বাচন করুন এবং রক্তচাপ রিডিং দিন' },
  VITALS_SAVE_FAILED:             { en: 'Failed to save vitals',                   bn: 'ভাইটাল সেভ করতে ব্যর্থ' },
  VITALS_SAVED_SUCCESS:           { en: 'Vitals saved successfully',               bn: 'ভাইটাল সফলভাবে সেভ হয়েছে' },
  VITALS_RISK_SCORE:              { en: 'Risk Score:',                             bn: 'ঝুঁকি স্কোর:' },
  VITALS_LEVEL:                   { en: 'Level:',                                  bn: 'মাত্রা:' },
  VITALS_SAVING:                  { en: 'Saving...',                               bn: 'সেভ হচ্ছে...' },
  VITALS_SAVE:                    { en: 'Save Vitals',                             bn: 'ভাইটাল সেভ করুন' },
  VITALS_BACK_TO_PATIENT:         { en: '← Back to Patient',                       bn: '← রোগীতে ফিরুন' },

  // ── Admin Dashboard ──────────────────────────────────────
  ADMIN_DASHBOARD_TITLE:          { en: 'Dashboard',                               bn: 'ড্যাশবোর্ড' },
  ADMIN_LOADING_STATS:            { en: 'Loading administrative statistics…',       bn: 'প্রশাসনিক পরিসংখ্যান লোড হচ্ছে…' },
  ADMIN_KPI_TOTAL_PATIENTS:       { en: 'Total Patients',                          bn: 'মোট রোগী' },
  ADMIN_KPI_HIGH_RISK:            { en: 'High Risk Cases',                         bn: 'উচ্চ ঝুঁকির কেস' },
  ADMIN_KPI_MODERATE_RISK:        { en: 'Moderate Risk Cases',                     bn: 'মাঝারি ঝুঁকির কেস' },
  ADMIN_KPI_ACTIVE_WORKERS:       { en: 'Active Health Workers',                   bn: 'সক্রিয় স্বাস্থ্যকর্মী' },
  ADMIN_RISK_TRENDS:              { en: 'Maternal Risk Trends',                    bn: 'মাতৃত্বকালীন ঝুঁকি প্রবণতা' },
  ADMIN_PATIENTS_BY_REGION:       { en: 'Patients by Region',                      bn: 'অঞ্চল অনুসারে রোগী' },
  ADMIN_REALTIME_ALERTS:          { en: 'Real-time Alerts',                        bn: 'রিয়েল-টাইম সতর্কতা' },
  ADMIN_ACTIVE_COUNT:             { en: '{count} Active',                          bn: '{count} সক্রিয়' },
  ADMIN_DEFAULT_ALERT_TITLE:      { en: 'System Initialized',                     bn: 'সিস্টেম চালু হয়েছে' },
  ADMIN_DEFAULT_ALERT_MSG:        { en: 'PulseGuard maternal health server is fully functional and ready.', bn: 'পালসগার্ড মাতৃস্বাস্থ্য সার্ভার সম্পূর্ণরূপে কার্যকর এবং প্রস্তুত।' },

  // ── Admin Analytics ──────────────────────────────────────
  ANALYTICS_TITLE:                { en: 'AI Analytics',                            bn: 'এআই বিশ্লেষণ' },
  ANALYTICS_LOADING:              { en: 'Loading analytical datasets…',            bn: 'বিশ্লেষণমূলক ডেটাসেট লোড হচ্ছে…' },
  ANALYTICS_REGION:               { en: 'Region',                                  bn: 'অঞ্চল' },
  ANALYTICS_ALL_REGIONS:          { en: 'All Regions',                             bn: 'সকল অঞ্চল' },
  ANALYTICS_RISK_CONDITION:       { en: 'Risk Condition',                          bn: 'ঝুঁকির অবস্থা' },
  ANALYTICS_ALL_CONDITIONS:       { en: 'All Conditions',                          bn: 'সকল অবস্থা' },
  ANALYTICS_PREECLAMPSIA:         { en: 'Preeclampsia',                            bn: 'প্রি-একলাম্পসিয়া' },
  ANALYTICS_ANEMIA:               { en: 'Anemia',                                  bn: 'রক্তস্বল্পতা' },
  ANALYTICS_GESTATIONAL_DIABETES: { en: 'Gestational Diabetes',                    bn: 'গর্ভকালীন ডায়াবেটিস' },
  ANALYTICS_RISK_DISTRIBUTION:    { en: 'Risk Distribution',                       bn: 'ঝুঁকি বিতরণ' },
  ANALYTICS_RISK_TRENDS:          { en: 'Risk Trends Over Time',                   bn: 'সময়ের সাথে ঝুঁকির প্রবণতা' },
  ANALYTICS_MODEL_PERFORMANCE:    { en: 'AI Model Performance',                    bn: 'এআই মডেল পারফরম্যান্স' },
  ANALYTICS_MODEL_DESC:           { en: 'XGBoost risk prediction model, last updated May 25, 2026', bn: 'XGBoost ঝুঁকি পূর্বাভাস মডেল, সর্বশেষ আপডেট ২৫ মে, ২০২৬' },
  ANALYTICS_ACCURACY:             { en: 'Accuracy',                                bn: 'নির্ভুলতা' },
  ANALYTICS_PRECISION:            { en: 'Precision',                               bn: 'প্রিসিশন' },
  ANALYTICS_RECALL:               { en: 'Recall',                                  bn: 'রিকল' },
  ANALYTICS_F1_SCORE:             { en: 'F1 Score',                                bn: 'F1 স্কোর' },
  ANALYTICS_PREDICTION_BREAKDOWN: { en: 'Prediction Breakdown',                    bn: 'পূর্বাভাস বিশ্লেষণ' },
  ANALYTICS_PREECLAMPSIA_RISK:    { en: 'Preeclampsia Risk',                       bn: 'প্রি-একলাম্পসিয়া ঝুঁকি' },
  ANALYTICS_CRITICAL_CASES:       { en: '{count} critical cases currently monitored', bn: '{count} সংকটপূর্ণ কেস বর্তমানে পর্যবেক্ষণ করা হচ্ছে' },
  ANALYTICS_BADGE_CRITICAL:       { en: 'Critical',                                bn: 'সংকটপূর্ণ' },
  ANALYTICS_MODERATE_CASES:       { en: '{count} patients requiring routine follow-ups', bn: '{count} রোগীর নিয়মিত ফলো-আপ প্রয়োজন' },
  ANALYTICS_BADGE_MODERATE:       { en: 'Moderate',                                bn: 'মাঝারি' },
  ANALYTICS_LOW_CASES:            { en: '{count} patients within normal thresholds', bn: '{count} রোগী স্বাভাবিক সীমার মধ্যে' },
  ANALYTICS_BADGE_NORMAL:         { en: 'Normal',                                  bn: 'স্বাভাবিক' },

  // ── Admin Patients ───────────────────────────────────────
  ADMIN_PATIENTS_TITLE:           { en: 'Patient Management',                      bn: 'রোগী ব্যবস্থাপনা' },
  ADMIN_PATIENTS_SEARCH:          { en: 'Search patients by name, village, or ID...', bn: 'নাম, গ্রাম বা আইডি দিয়ে রোগী খুঁজুন...' },
  ADMIN_PATIENTS_ADD:             { en: '+ Add Patient',                           bn: '+ রোগী যোগ করুন' },
  ADMIN_PATIENTS_LOADING:         { en: 'Loading patients list…',                  bn: 'রোগীর তালিকা লোড হচ্ছে…' },
  ADMIN_PATIENTS_EMPTY:           { en: 'No patients found matching the criteria.', bn: 'মানদণ্ডের সাথে মিলে এমন কোনো রোগী পাওয়া যায়নি।' },
  ADMIN_PATIENTS_SHOWING:         { en: 'Showing {filtered} of {total} patients',  bn: '{total} রোগীর মধ্যে {filtered} জন দেখাচ্ছে' },
  ADMIN_PATIENTS_VIEW_DETAILS:    { en: 'View Details',                            bn: 'বিস্তারিত দেখুন' },
  ADMIN_PATIENTS_CREATE_TITLE:    { en: 'Create Patient Profile',                  bn: 'রোগীর প্রোফাইল তৈরি করুন' },
  ADMIN_PATIENTS_NAME_REQUIRED:   { en: 'Name is required',                        bn: 'নাম আবশ্যক' },
  ADMIN_PATIENTS_CREATE_FAILED:   { en: 'Failed to create patient',               bn: 'রোগী তৈরি করতে ব্যর্থ' },
  ADMIN_PATIENTS_LABEL_NAME:      { en: 'Full Name *',                             bn: 'পূর্ণ নাম *' },
  ADMIN_PATIENTS_PLACEHOLDER_NAME: { en: 'Amina Rahman',                           bn: 'আমিনা রহমান' },
  ADMIN_PATIENTS_LABEL_AGE:       { en: 'Age (years)',                             bn: 'বয়স (বছর)' },
  ADMIN_PATIENTS_LABEL_VILLAGE:   { en: 'Village',                                 bn: 'গ্রাম' },
  ADMIN_PATIENTS_PLACEHOLDER_VILLAGE: { en: 'Kurigram Village A',                  bn: 'কুড়িগ্রাম গ্রাম ক' },
  ADMIN_PATIENTS_LABEL_GESTATIONAL: { en: 'Gestational Week',                      bn: 'গর্ভাবস্থার সপ্তাহ' },
  ADMIN_PATIENTS_CREATING:        { en: 'Creating...',                             bn: 'তৈরি হচ্ছে...' },
  ADMIN_PATIENTS_CREATE:          { en: 'Create',                                  bn: 'তৈরি করুন' },

  // ── Admin Table Headers ──────────────────────────────────
  TABLE_PATIENT_ID:               { en: 'Patient ID',                              bn: 'রোগী আইডি' },
  TABLE_NAME:                     { en: 'Name',                                    bn: 'নাম' },
  TABLE_RISK_LEVEL:               { en: 'Risk Level',                              bn: 'ঝুঁকির মাত্রা' },
  TABLE_WEEK:                     { en: 'Week',                                    bn: 'সপ্তাহ' },
  TABLE_ASSIGNED_WORKER:          { en: 'Assigned Worker',                         bn: 'নির্ধারিত কর্মী' },
  TABLE_LAST_UPDATED:             { en: 'Last Updated',                            bn: 'সর্বশেষ আপডেট' },
  TABLE_ACTIONS:                  { en: 'Actions',                                 bn: 'কার্যক্রম' },
  TABLE_USER_ID:                  { en: 'User ID',                                 bn: 'ব্যবহারকারী আইডি' },
  TABLE_ROLE:                     { en: 'Role',                                    bn: 'ভূমিকা' },
  TABLE_EMAIL:                    { en: 'Email',                                   bn: 'ইমেইল' },
  TABLE_PHONE:                    { en: 'Phone',                                   bn: 'ফোন' },
  TABLE_CREATED_AT:               { en: 'Created At',                              bn: 'তৈরির তারিখ' },
  UNASSIGNED:                     { en: 'Unassigned',                              bn: 'অনির্ধারিত' },

  // ── Admin Reports ────────────────────────────────────────
  REPORTS_TITLE:                  { en: 'Reports',                                 bn: 'রিপোর্ট' },
  REPORTS_LOADING:                { en: 'Loading reports definitions…',            bn: 'রিপোর্ট সংজ্ঞা লোড হচ্ছে…' },
  REPORTS_LAST_GENERATED:         { en: 'Last generated:',                         bn: 'সর্বশেষ তৈরি:' },
  REPORTS_EXPORT_CSV:             { en: 'Export CSV',                               bn: 'CSV রপ্তানি' },
  REPORTS_NO_DATA:                { en: 'No patient data available to export.',    bn: 'রপ্তানির জন্য কোনো রোগীর ডেটা নেই।' },
  REPORT_MATERNAL_HEALTH:         { en: 'Maternal Health Report',                  bn: 'মাতৃস্বাস্থ্য রিপোর্ট' },
  REPORT_MATERNAL_HEALTH_DESC:    { en: 'Comprehensive monthly summary of maternal health outcomes, risk distributions, and intervention effectiveness across all regions.', bn: 'সকল অঞ্চলে মাতৃস্বাস্থ্যের ফলাফল, ঝুঁকি বিতরণ এবং হস্তক্ষেপ কার্যকারিতার বিস্তারিত মাসিক সারসংক্ষেপ।' },
  REPORT_RISK_ANALYSIS:          { en: 'Risk Analysis Report',                     bn: 'ঝুঁকি বিশ্লেষণ রিপোর্ট' },
  REPORT_RISK_ANALYSIS_DESC:     { en: 'AI-powered risk prediction breakdown including preeclampsia, anemia, and gestational diabetes detection rates.', bn: 'এআই-চালিত ঝুঁকি পূর্বাভাস বিশ্লেষণ যার মধ্যে প্রি-একলাম্পসিয়া, রক্তস্বল্পতা এবং গর্ভকালীন ডায়াবেটিস সনাক্তকরণের হার অন্তর্ভুক্ত।' },
  REPORT_FIELD_ACTIVITY:         { en: 'Field Activity Report',                    bn: 'মাঠ কার্যক্রম রিপোর্ট' },
  REPORT_FIELD_ACTIVITY_DESC:    { en: 'Health worker performance summary — visits completed, patients served, sync compliance, and response times.', bn: 'স্বাস্থ্যকর্মীর কর্মক্ষমতা সারসংক্ষেপ — সম্পন্ন ভিজিট, সেবাপ্রাপ্ত রোগী, সিঙ্ক সম্মতি এবং প্রতিক্রিয়া সময়।' },
  REPORT_SYNC_STATUS:            { en: 'Sync Status Report',                       bn: 'সিঙ্ক অবস্থা রিপোর্ট' },
  REPORT_SYNC_STATUS_DESC:       { en: 'Offline device analytics, sync success rates, conflict resolution metrics, and data integrity audit.', bn: 'অফলাইন ডিভাইস বিশ্লেষণ, সিঙ্ক সাফল্যের হার, দ্বন্দ্ব সমাধান মেট্রিক্স এবং ডেটা অখণ্ডতা অডিট।' },

  // ── Admin Settings ───────────────────────────────────────
  SETTINGS_TITLE:                 { en: 'Settings',                                bn: 'সেটিংস' },
  SETTINGS_USER_MANAGEMENT:       { en: 'User Management',                         bn: 'ব্যবহারকারী ব্যবস্থাপনা' },
  SETTINGS_USER_MANAGEMENT_DESC:  { en: 'Manage health workers, patients, and admin accounts. Assign roles and configure permissions.', bn: 'স্বাস্থ্যকর্মী, রোগী এবং অ্যাডমিন অ্যাকাউন্ট পরিচালনা করুন। ভূমিকা নির্ধারণ এবং অনুমতি কনফিগার করুন।' },
  SETTINGS_MANAGE_USERS:          { en: 'Manage Users',                            bn: 'ব্যবহারকারী পরিচালনা' },
  SETTINGS_AI_CONFIG:             { en: 'AI Configuration',                        bn: 'এআই কনফিগারেশন' },
  SETTINGS_AI_CONFIG_DESC:        { en: 'Set risk prediction thresholds, model selection (XGBoost/Llama 3), and alert sensitivity levels.', bn: 'ঝুঁকি পূর্বাভাস থ্রেশহোল্ড, মডেল নির্বাচন (XGBoost/Llama 3) এবং সতর্কতা সংবেদনশীলতা স্তর সেট করুন।' },
  SETTINGS_CONFIGURE_AI:          { en: 'Configure AI',                            bn: 'এআই কনফিগার' },
  SETTINGS_OFFLINE_SYNC:          { en: 'Offline & Sync Settings',                 bn: 'অফলাইন ও সিঙ্ক সেটিংস' },
  SETTINGS_OFFLINE_SYNC_DESC:     { en: 'Configure sync frequency, conflict resolution mode (auto-merge vs manual), and storage limits.', bn: 'সিঙ্ক ফ্রিকোয়েন্সি, দ্বন্দ্ব সমাধান মোড (অটো-মার্জ বনাম ম্যানুয়াল) এবং স্টোরেজ সীমা কনফিগার করুন।' },
  SETTINGS_UPDATE:                { en: 'Update Settings',                         bn: 'সেটিংস আপডেট' },
  SETTINGS_LANGUAGE:              { en: 'Language Settings',                        bn: 'ভাষা সেটিংস' },
  SETTINGS_LANGUAGE_DESC:         { en: 'Configure Bengali and English language support. Set default language for AI responses.', bn: 'বাংলা এবং ইংরেজি ভাষা সমর্থন কনফিগার করুন। এআই প্রতিক্রিয়ার জন্য ডিফল্ট ভাষা সেট করুন।' },
  SETTINGS_MANAGE_LANGUAGES:      { en: 'Manage Languages',                        bn: 'ভাষা পরিচালনা' },
  SETTINGS_COMING_SOON:           { en: 'Feature Coming Soon!\nThe "{title}" configuration panel is disabled for this hackathon demo version.', bn: 'ফিচার শীঘ্রই আসছে!\n"{title}" কনফিগারেশন প্যানেলটি এই হ্যাকাথন ডেমো সংস্করণে নিষ্ক্রিয়।' },
  SETTINGS_SYSTEM_INFO:           { en: 'System Information',                      bn: 'সিস্টেম তথ্য' },
  SETTINGS_VERSION:               { en: 'Version',                                 bn: 'সংস্করণ' },
  SETTINGS_VERSION_VALUE:         { en: 'PulseGuard v1.0.0',                       bn: 'পালসগার্ড v1.0.0' },
  SETTINGS_STACK:                 { en: 'Stack',                                   bn: 'স্ট্যাক' },
  SETTINGS_STACK_VALUE:           { en: 'PERN + Python AI',                        bn: 'PERN + পাইথন এআই' },
  SETTINGS_AI_MODELS:             { en: 'AI Models',                               bn: 'এআই মডেল' },
  SETTINGS_AI_MODELS_VALUE:       { en: 'Llama 3 + XGBoost',                       bn: 'Llama 3 + XGBoost' },
  SETTINGS_DATABASE:              { en: 'Database',                                bn: 'ডেটাবেস' },
  SETTINGS_DATABASE_VALUE:        { en: 'PostgreSQL + pgvector',                   bn: 'PostgreSQL + pgvector' },

  // ── Admin Users ──────────────────────────────────────────
  USERS_TITLE:                    { en: 'User Management',                         bn: 'ব্যবহারকারী ব্যবস্থাপনা' },
  USERS_SEARCH:                   { en: 'Search users by name, email, phone, or role...', bn: 'নাম, ইমেইল, ফোন বা ভূমিকা দিয়ে ব্যবহারকারী খুঁজুন...' },
  USERS_ADD:                      { en: '+ Add User',                              bn: '+ ব্যবহারকারী যোগ করুন' },
  USERS_LOADING:                  { en: 'Loading users list…',                     bn: 'ব্যবহারকারী তালিকা লোড হচ্ছে…' },
  USERS_EMPTY:                    { en: 'No users found matching the criteria.',   bn: 'মানদণ্ডের সাথে মিলে এমন কোনো ব্যবহারকারী পাওয়া যায়নি।' },
  USERS_SHOWING:                  { en: 'Showing {filtered} of {total} users',     bn: '{total} ব্যবহারকারীর মধ্যে {filtered} জন দেখাচ্ছে' },
  USERS_CONFIRM_DELETE:           { en: 'Are you sure you want to delete {name}?', bn: 'আপনি কি নিশ্চিত যে {name} মুছতে চান?' },
  USERS_DELETE_FAILED:            { en: 'Failed to delete user',                   bn: 'ব্যবহারকারী মুছতে ব্যর্থ' },
  USERS_CREATE_TITLE:             { en: 'Create User Account',                     bn: 'ব্যবহারকারী অ্যাকাউন্ট তৈরি' },
  USERS_CREATE_FAILED:            { en: 'Failed to create user',                   bn: 'ব্যবহারকারী তৈরি করতে ব্যর্থ' },
  USERS_NAME_PASS_REQUIRED:       { en: 'Name and password are required',          bn: 'নাম এবং পাসওয়ার্ড আবশ্যক' },
  USERS_EMAIL_PHONE_REQUIRED:     { en: 'Either email or phone is required',       bn: 'ইমেইল বা ফোন যেকোনো একটি আবশ্যক' },
  USERS_LABEL_NAME:               { en: 'Full Name *',                             bn: 'পূর্ণ নাম *' },
  USERS_PLACEHOLDER_NAME:         { en: 'e.g. Dr. Sarah Rahman',                  bn: 'যেমন ডাঃ সারাহ রহমান' },
  USERS_LABEL_EMAIL:              { en: 'Email',                                   bn: 'ইমেইল' },
  USERS_PLACEHOLDER_EMAIL:        { en: 'sarah@pulseguard.com',                    bn: 'sarah@pulseguard.com' },
  USERS_PLACEHOLDER_PHONE:        { en: '+8801700000000',                          bn: '+8801700000000' },
  USERS_LABEL_PASSWORD:           { en: 'Password *',                              bn: 'পাসওয়ার্ড *' },
  USERS_PLACEHOLDER_PASSWORD:     { en: 'Min. 6 characters',                       bn: 'সর্বনিম্ন ৬ অক্ষর' },
  USERS_LABEL_ROLE:               { en: 'Role *',                                  bn: 'ভূমিকা *' },
  USERS_OPTION_WORKER:            { en: 'Health Worker',                           bn: 'স্বাস্থ্যকর্মী' },
  USERS_OPTION_ADMIN:             { en: 'Administrator',                           bn: 'প্রশাসক' },
  USERS_CREATING:                 { en: 'Creating...',                             bn: 'তৈরি হচ্ছে...' },
  USERS_CREATE:                   { en: 'Create User',                             bn: 'ব্যবহারকারী তৈরি' },
  USERS_CHIP_WORKERS:             { en: 'Workers: {count}',                        bn: 'কর্মী: {count}' },
  USERS_CHIP_ADMINS:              { en: 'Admins: {count}',                         bn: 'অ্যাডমিন: {count}' },
  USERS_CHIP_PATIENTS:            { en: 'Patients: {count}',                       bn: 'রোগী: {count}' },

  // ── Admin Layout / Mobile Layout ─────────────────────────
  ADMIN_SUBTITLE:                 { en: 'PulseGuard AI, Admin Console',            bn: 'পালসগার্ড এআই, অ্যাডমিন কনসোল' },
  ADMIN_SIDEBAR_VERSION:          { en: 'PulseGuard AI v1.0.0',                    bn: 'পালসগার্ড এআই v1.0.0' },
  ADMIN_SIDEBAR_TAGLINE:          { en: 'Offline-First Maternal Healthcare',       bn: 'অফলাইন-ফার্স্ট মাতৃস্বাস্থ্য সেবা' },
  MOBILE_SUBTITLE_WORKER:         { en: 'Maternal Health Worker Portal',           bn: 'মাতৃস্বাস্থ্যকর্মী পোর্টাল' },
  MOBILE_SUBTITLE_PATIENT:        { en: 'Patient Portal',                          bn: 'রোগী পোর্টাল' },
  MOBILE_SUBTITLE_PREFIX:         { en: 'PulseGuard AI:',                          bn: 'পালসগার্ড এআই:' },
  TOGGLE_CONNECTIVITY:            { en: 'Click to toggle connectivity state',      bn: 'সংযোগ অবস্থা পরিবর্তন করতে ক্লিক করুন' },
  BANNER_DEFAULT_TITLE:           { en: 'Status',                                  bn: 'অবস্থা' },

  // ── Chart Labels ─────────────────────────────────────────
  CHART_TOTAL_PATIENTS:           { en: 'Total Patients',                          bn: 'মোট রোগী' },
  CHART_HIGH_RISK:                { en: 'High Risk',                               bn: 'উচ্চ ঝুঁকি' },
  CHART_MODERATE_RISK:            { en: 'Moderate Risk',                           bn: 'মাঝারি ঝুঁকি' },
  CHART_LOW_RISK:                 { en: 'Low Risk',                                bn: 'নিম্ন ঝুঁকি' },

  // ── Notifications (AppContext) ───────────────────────────
  NOTIF_HIGH_RISK_TITLE:          { en: 'High Risk Alert',                         bn: 'উচ্চ ঝুঁকি সতর্কতা' },
  NOTIF_RISK_MESSAGE:             { en: 'Risk score: {score}',                     bn: 'ঝুঁকি স্কোর: {score}' },
  NOTIF_SOS_PREFIX:               { en: '🚨 SOS:',                                bn: '🚨 এসওএস:' },
  NOTIF_SOS_MESSAGE:              { en: 'Emergency SOS dispatched!',               bn: 'জরুরি এসওএস প্রেরিত!' },

  // ── Admin Patients Chips ─────────────────────────────────
  CHIP_HIGH_RISK:                 { en: 'High Risk: {count}',                      bn: 'উচ্চ ঝুঁকি: {count}' },
  CHIP_MODERATE:                  { en: 'Moderate: {count}',                       bn: 'মাঝারি: {count}' },
  CHIP_LOW:                       { en: 'Low: {count}',                            bn: 'নিম্ন: {count}' },
}

/**
 * Translate a string key to a specific locale.
 * Supports template interpolation with {key} syntax.
 *
 * @param {string} key - The string key to look up
 * @param {string} locale - 'en' or 'bn'
 * @param {Object} params - Optional interpolation parameters
 * @returns {string} The translated string
 *
 * @example
 * $('BRAND_NAME', 'bn')               // → 'পালসগার্ড'
 * $('DASHBOARD_WELCOME', 'bn', { name: 'Amina' }) // → 'স্বাগতম, Amina!'
 */
const $ = (key, locale = 'bn', params = {}) => {
  const entry = strings[key]
  if (!entry) {
    console.warn(`[i18n] Missing key: "${key}"`)
    return key
  }
  let text = entry[locale] || entry['en'] || key
  // Template interpolation: replace {varName} with params.varName
  if (params && typeof params === 'object') {
    Object.keys(params).forEach((param) => {
      text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param])
    })
  }
  return text
}

export default $